### ISSUE TITLE
http://www.nbc.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4182] opened 2017-01-24 12:25 UTC
http://www.nbc.com/the-celebrity-apprentice/video/scissors-and-some-creativity/3456384

![image](https://cloud.githubusercontent.com/assets/15856304/22247019/6465ba98-e240-11e6-930c-794554d8aeaf.png)

<details>

Reproduced on Mac, 1.4. Chrome 55, English, Russian, SM filter, Annoyances, Spyware, Safari and Mobile ads filter.

**Comment by evgeniy-ADG** [comment] 2017-02-19 13:30
http://www.cnbc.com/2017/02/17/marine-le-pen-could-blow-up-european-union-fear-in-bond-market.html

![image](https://cloud.githubusercontent.com/assets/15856304/23102741/8beca852-f6b7-11e6-97ef-d59a9cbd621e.png)

The same set of filters, all up to date.

**Comment by Alex-302** [comment] 2017-02-20 15:11
I can't reproduce, because regional restrictions. What proxy or vpn are you using?

**Comment by seanl-adg** [comment] 2017-02-22 13:21
The video plays on my end, I can't reproduce the adblock detection screen.

**Comment by evgeniy-ADG** [comment] 2017-02-22 13:39
Works today, didn't work 2 days ago. I've made the screenshot, have been using our regular Ukrainian ip.

**Comment by Alex-302** [comment] 2017-02-22 15:29
Maybe it was fixed in EasyList.

**Comment by evgeniy-ADG** [comment] 2017-05-04 09:01
It's back.

![image](https://cloud.githubusercontent.com/assets/15856304/25696830/522b1650-30c1-11e7-8177-c1dde1394d1f.png)

Reproduced in Chrome, 

![image](https://cloud.githubusercontent.com/assets/15856304/25696850/6ff62e68-30c1-11e7-9a70-1a8a4826d949.png)

**Comment by seanl-adg** [comment] 2017-05-04 10:24
Not reproduced, could you provide a url that an issue can be reproduced?

**Comment by Alex-302** [comment] 2017-05-04 12:15
Reproduced with extension only.
Try
@@||npttech.com/advertising.js
or
cnbc.com##body > div.pico-content
cnbc.com##body > div.pico-overlay

**Closed** 2017-07-19 21:40 UTC
Labels: Anti Adblock Script, Resolved

**Comment by ghajini** [comment] 2017-09-23 15:12
hello sir,
@Alex-302 
antiadblock gone BUT video doesn't play on my end

link to test=
`https://www.nbc.com/emerald-city/video/they-came-first/3463424`
geolock= usa
console=
`http://prntscr.com/goqqw7`
`http://prntscr.com/goqr46`
`http://prntscr.com/goqr98`

**Comment by ghajini** [comment] 2017-09-24 12:33
@Alex-302 do i need to fill new bug report?

**Comment by Alex-302** [comment] 2017-09-24 14:41
Without AdGuard:
http://imagizer.imageshack.com/img924/8723/sXQSAb.png

@AdamWr please check on your end with US proxy.
