### ISSUE TITLE
123moviesfx.live

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90438] opened 2021-08-08 22:01 UTC
**Issue URL (Annoyance)**: https://123moviesfx.live/future-ways-of-living/

<details><summary>Screenshots:</summary>
4

![image](https://user-images.githubusercontent.com/76880977/128646988-a15a4eff-8d53-4ef3-b4b1-ced1b71a8418.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-08-11 11:46
Looks like duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/90093

**Closed by AdamWr** 2021-08-11 11:46 UTC
