### ISSUE TITLE
Anti-adblock on www.wenxuecity.com

### ISSUE THREAD

**Issue by sh2sg** [AdguardTeam/AdguardFilters#62923] opened 2020-09-02 04:21 UTC
***Description***:
* **Current behaviour**: 

https://www.wenxuecity.com/index.php

It started throwing Anti-Adbock popup recently, it seemed to come from Google so I added rule to block https://fundingchoicesmessages.google.com

Now popup disappeared but a banner appeared at the bottom of every page. The banner DIV has random number in its class name and style.

How can I filter such banner?

Or is there any other better method to filter anti-adbkock from this site?

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | macOS Catalina 10.15.6
Browser:                               | Safari  13.1.2 
AdGuard version:                       | 2.4.8.797
Filters enabled:                       | AdGuard base filter, AdGuard Tracking protection, AdGuard Annoyances filter, AdGuard warning removal list, EazyList China
AdGuard DNS:                           | None

**Comment by sh2sg** [comment] 2020-09-02 08:23
Awesome! It worked! I didn't know about this filter.

**Comment by AdamWr** [comment] 2020-09-03 10:15
Hi,
It seems to be a duplicate of this issue - https://github.com/AdguardTeam/AdguardFilters/issues/62881
It was fixed in `AdGuard Annoyances filter`, so please update filters.

**Closed by AdamWr** 2020-09-03 10:15 UTC
