### ISSUE TITLE
breakage gamingdeputy.com (for safari adguard)

### ISSUE THREAD

**Issue by xnusnim** [AdguardTeam/AdguardFilters#169814] opened 2024-01-03 02:13 UTC
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Safari

### AdGuard version

4.5.2

### What type of problem have you encountered?

Missed ads or ad leftovers, Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

http://gamingdeputy.com/

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. If you wait for about 15 seconds on the website, an error occurs that breaks the screen.
These problems are likely to cause users to leave.
I will use microShield, but please do not experience problems to users.

Filter inspection is required. the CSS of the website is being blocked.

The filter list I used is in Screenshot 1.
The problem screenshot is in Screenshot 2.

<details><summary>Screenshot 1:</summary>

<img width="396" alt="스크린샷 2024-01-03 오전 10 55 38" src="https://github.com/AdguardTeam/AdguardFilters/assets/81290656/d5c7ef7f-0905-4966-a3a0-14af76d9881f">

</details>

<details><summary>Screenshot 2:</summary>

<img width="409" alt="스크린샷 2024-01-03 오전 10 56 06" src="https://github.com/AdguardTeam/AdguardFilters/assets/81290656/d379c8ca-6faf-4489-ad13-bda8275862b6">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by xnusnim** [comment] 2024-01-03 02:32
@piquark6046
If adshield fails to block ads on protected websites, shouldn't Adguard handle the exception? Adguard will try to force a block, causing it to crash and ultimately ruining the user experience.

It is better to see advertisements than to have a broken website. So please handle the exception so that users don't experience this problem.

**Comment by piquark6046** [comment] 2024-01-03 02:41
The microShield userscript is too big to include AdGuard adblocker or AdGuard Extra userscript.
Because I pinned the related message, a reporter can see the message if the reporter reports the issue using AdGuard's anonymous reporting tool.

**Comment by piquark6046** [comment] 2024-01-03 02:42
Duplicate of #167382

**Closed** 2024-01-03 02:43 UTC
Labels: Unsorted
