### ISSUE TITLE
kingofdown.com - Adblock - Windows

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7062] opened 2017-10-09 19:30 UTC
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Anti-Adblock Script - kingofdown.com After visiting this site, a few
seconds later, it displays to disable the adblocker. 

You have to scroll a little to get the adblock popup.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31349172-d8be43b4-ad2a-11e7-8620-f651058fcf3b.png)

</details><br/>

**Filters:**

FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
FilterId:122 Name: Fanboy's Annoyances Url: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
FilterId:211 Name: Anti-Adblock Killer | Reek Url: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
FilterId:215 Name: Fanboy's Enhanced Tracking List Url: https://secure.fanboy.co.nz/enhancedstats.txt
FilterId:229 Name: I don't care about cookies Url: http://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/
FilterId:0 Name: User filter Url: no_url

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 6.1.7601 
AdGuard version:                    | 6.1.331.1732
AdGuard DNS:                        | None / Default / Family Protection
Helpdesk ID (if exists):            | 1518164

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment] 2017-10-10 09:42
Can't reproduce, It was fixed by `@@||kingofdown.com^$generichide` few weeks ago.

**Closed by Alex-302** 2017-10-10 09:42 UTC
Labels: Anti Adblock Script, Windows
