### ISSUE TITLE
la123movies.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#90239] opened 2021-08-06 05:43 UTC
**Issue URL (Ads)** : https://la123movies.com/episodes/obama-in-pursuit-of-a-more-perfect-union-season-1-episode-2/

<details><summary>Screenshots:</summary>

pop up to ![image](https://user-images.githubusercontent.com/76880977/128461973-cdb8cc17-e6bc-4cae-9f88-5ad8746d12fc.png) 

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Yuki2718** [comment] 2021-08-06 11:45
Should be fixed now, duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/90217

**Closed by Yuki2718** 2021-08-06 11:45 UTC

**Comment by chirag127** [comment] 2021-08-06 11:55
> duplicate of #90217

How? This issue is for ads not the annoyance.
I have seen this that is I only report ads . Alex Don't bother to remove to remove the annoyances or vice versa.

**Comment by Yuki2718** [comment] 2021-08-06 14:03
#90217 is also about ads, just a different appearance. This propeller crap do some different staff depending on something.

**Comment by chirag127** [comment] 2021-08-06 14:40
> #90217 is also about ads, just a different appearance

Ah , so the guy had mentioned a different reason that's more heinous . I have often seen that Alex just close the issue if I mistakenly mention the reason Ads instead of annoyance and then I have to recreate the issue to get it solved by someone.
