### ISSUE TITLE
Dailyhunt (Newshunt) News app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3024] opened 2016-09-18 13:31 UTC
https://play.google.com/store/apps/details?id=com.eterno

![image](https://cloud.githubusercontent.com/assets/15856304/18616030/365bccec-7dbd-11e6-8a13-5b7ece560bef.png)

Ad URLs look like that 
<details>
http://api.taboola.com/1.1/json/dailyhunt-dailyhunt/recommendations.notify-click?app.type=mobile&app.apikey=fe1d97b62eed790e867ad2115d7a9f92abc97940&response.id=__7765884cbc95f60bf6acb02419f64729__c0e78d7a871f54ec4c6b3f7cdd580449&response.session=v2_a90d667e9a4c8b016d3267e400f79569_ODU1NzQxNjU0_1474041575_1474041575_CNawjgYQlO4_GPjs5Z3zKiAB&item.id=%7E%7EV1%7E%7E5687969138830016482%7E%7EWOQg3BA73-LWxGcq-0Qk1J4JOr4oaIVKPSHmPI1FXVic6r7iXmJnIqxym_QIcG8bIpGMidGrnq55vOGsK40tcQ&item.type=photo&redir=http%3A%2F%2Fradaronline.com%2Fphotos%2Fstupid-celebrity-quotes%2F%3Futm_source%3Dtaboola2%26utm_medium%3Dcpc%26utm_content%3DNot%2BEvery%2BStar%2BThinks%2BBefore%2BThey%2BSpeak%2521%2B25%2BReally%2BStupid%2BCelebrity%2BQuotes%26utm_campaign%3Ddailyhunt-dailyhunt&cl_id=ODU1NzQxNjU0
</details>

HTTPS, HQ mode + eng, social, annoyances, russain

**Comment by Alex-302** [comment] 2016-09-18 15:05
Please check this rule:
```
||taboola.com^$app=com.eterno
```

**Comment by GSM789** [comment] 2016-09-18 17:17
Dir Alex-302 & evgeniy-ADG ,
 great thanks..
 i tried this rule and working 50% PERFECTLY...  
Now the ads and its element are hidden/blocked in my native language news... 

But now the problem is --- its only working with my native language. When i chage to english as a news language, the ads & its element r back !!!!!!! (taboola.com)... 
Any solution!!

**Comment by GSM789** [comment] 2016-09-19 05:39
Dir alex-302 & evgeniy-ADG , 
thanks 
I tried Your rule ..
It was working..  
but  TODAY ALL ADS ARE BACK....
Any hope !!!!!

**Comment by GSM789** [comment] 2016-09-19 05:40
Dir alex-302 & evgeniy-ADG , 
thanks 
I tried Your rule ..
It was working..  
but  TODAY ALL ADS ARE BACK....
Any hope !!!!!

**Comment by Alex-302** [comment] 2016-09-20 06:05
Provide your logs, please.

**Comment by GSM789** [comment] 2016-09-20 06:11
Dir Alex-302, 
That u mean Har file of Adguard?? Or getting log file in another way!!
pls tell me the way to get log file...

**Comment by Alex-302** [comment] 2016-09-20 06:18
for HAR
https://kb.adguard.com/index.php?/Russian/Knowledgebase/Article/View/65/0/how-to-get-har-http-archive-files-from-android-device
for log
https://kb.adguard.com/index.php?/Russian/Knowledgebase/Article/View/49/0/collecting-a-full-log-on-adguard-for-android
I need HTTP log.
Please clear cache of that app and close it completely before the next attempt.

**Comment by GSM789** [comment] 2016-09-20 07:29
The dailyhunt HAR files are here ...
(I made few changes in it)...


[dailyhunt_har.txt](https://github.com/AdguardTeam/AdguardFilters/files/481835/dailyhunt_har.txt)

[dailyhunt_har_1474353004788.txt](https://github.com/AdguardTeam/AdguardFilters/files/481836/dailyhunt_har_1474353004788.txt)

.

**Comment by Alex-302** [comment] 2016-09-20 07:34
Please send me logs(look at above) via our support.

**Comment by GSM789** [comment] 2016-09-20 11:20
Hi alex-302, 
Dailyhunt Log file
(I made few changes in it)...

[adguardlog.txt](https://github.com/AdguardTeam/AdguardFilters/files/482369/adguardlog.txt)

.

**Comment by Alex-302** [comment] 2016-09-20 19:09
Thanks. Found this ad.
Added to Mobile filter
```
||ctl.buyt.in^$empty
```

**Comment by Bohdan-SUP** [comment] 2016-09-25 00:09
Looks like it's back:
<details>
![screenshot_2016-09-23-21-14-20](https://cloud.githubusercontent.com/assets/14153331/18812001/7a17c070-82cd-11e6-8918-b596ec4099b5.png)
![screenshot_2016-09-23-21-18-19](https://cloud.githubusercontent.com/assets/14153331/18812000/7a163d54-82cd-11e6-987d-efb7a72b3f1d.png)
</details>

Log:
[edited.Log.dailyhnt.latest.txt](https://github.com/AdguardTeam/AdguardFilters/files/491430/edited.Log.dailyhnt.latest.txt)

**Comment by Alex-302** [comment] 2016-09-25 11:23
They are blocked. You should to clear caсру or the app data.

**Comment by Yana-SUP** [comment] 2016-12-02 12:37
User says "After opening a news to read and when I touch to scroll down,
every single news articles r redirecting to a sponsored advertisement page"

log:
[adguard.log (3).txt](https://github.com/AdguardTeam/AdguardFilters/files/627144/adguard.log.3.txt)

Screenshots: http://prnt.sc/deg461
http://prnt.sc/deg4cj
http://prnt.sc/deg4jk

**Comment by Alex-302** [comment] 2016-12-03 15:13
@seanl-adg please try to fix it

**Comment by GSM789** [comment] 2016-12-03 17:22
Few of these dns making ads and redirecting to the ad page..
When i add this to my system host list , then no redirected sponsored "ad page".... And no banner ads...
But actually i don't know which one is making ads....  Pls check it... 

![screenshot_2016-12-03-21-59-05](https://cloud.githubusercontent.com/assets/22278693/20860980/92e82036-b9aa-11e6-89d9-5d53bf087d4d.png)

![screenshot_2016-12-03-22-04-16](https://cloud.githubusercontent.com/assets/22278693/20860987/c1798de0-b9aa-11e6-8555-92995fdcec17.png)



[my export DNS.txt](https://github.com/AdguardTeam/AdguardFilters/files/628989/my.export.DNS.txt)


......

**Comment by Alex-302** [comment] 2016-12-05 13:20
Added to Mobile filter
```
||graph.facebook.com^$app=com.eterno
||api-news.dailyhunt.in/api/*/content?$replace=/externalAd/_externalAd/
```
check these rules

**Comment by GSM789** [comment] 2016-12-05 13:41
Dir ALEX-302 , 
         😍😍😍😍😍..... U R THE REAL GENIUS..... 😍😍😍😍😍

These rules r working perfectly.......

Thank you ALEX-302 , thank u YANA-SUP , thank u ADGUARD........

**Comment by GSM789** [comment] 2016-12-05 13:49
Dir ALEX-302 ,
😍😍😍😍😍..... **U R THE REAL GENIUS**..... 😍😍😍😍😍

These rules r working perfectly.......

Thank you @Alex-302  , thank u @Yana-SUP , thank u ADGUARD........

**Comment by GSM789** [comment] 2016-12-05 13:52
Dir ALEX-302,
😍😍😍😍😍..... **U R THE REAL GENIUS**..... 😍😍😍😍😍

These rules r working perfectly.......

Thank you @Alex-302 , thank u @Yana-SUP , thank u **ADGUARD**........

**Closed** 2016-12-05 13:52 UTC
Labels: Ads
