### ISSUE TITLE
www.indiatoday.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99076] opened 2021-11-05 16:20 UTC
**Issue URL (Ads/Annoyance)**:https://www.indiatoday.in/technology/news/story/india-ranks-70th-worldwide-in-fixed-broadband-speeds-records-average-download-speed-of-58-17mbps-1829967-2021-07-19

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/140543570-d539197b-7ae5-4404-ba65-6f4823a1c2a3.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-11-09 13:49
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/98467

**Closed by AdamWr** 2021-11-09 13:49 UTC
