### ISSUE TITLE
freetutorialsudemy.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94298] opened 2021-09-10 16:54 UTC
**Issue URL (Anti Adblock Script/Annoyance):**https://freetutorialsudemy.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132889740-355ff1ad-a498-44f8-86ce-2bb55691db6d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-09-24 08:42
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/93907

**Closed by AdamWr** 2021-09-24 08:42 UTC
