### ISSUE TITLE
www.indiatoday.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98607] opened 2021-10-31 11:07 UTC
**Issue URL (Ads/Annoyance)**:
https://www.indiatoday.in/india/story/indian-navy-receives-first-p15b-guided-missile-destroyer-1871584-2021-10-31

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/139579865-8eaaa9dd-dc04-454c-8078-96c874034f28.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-11-09 13:49
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/98467

**Closed by AdamWr** 2021-11-09 13:49 UTC
