### ISSUE TITLE
[Windows] www.windowscentral.com - anti adblock script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#3878] opened 2016-12-26 00:23 UTC
![](http://i.imgur.com/KHfEDk9.jpg)
http://www.windowscentral.com/windows-10-build-14997-leaks-web-new-features-and-changes

**Adguard version**: 6.1.298.1564

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment] 2016-12-26 13:50
please check
```
windowscentral.com#@#.adunit
```

**Comment by danidoedel** [comment] 2016-12-28 12:29
@Alex-302 Doesn't work. At least not on mobile, couldn't test on my PC yet.

**Comment by Alex-302** [comment] 2016-12-28 12:48
Strange. It works fine on my droid and PC.

**Comment by danidoedel** [comment] 2017-01-08 17:49
@Vincent-Michael Still not fixed on mobile...

**Comment by Alex-302** [comment] 2017-01-09 20:54
@danidoedel which OS?

**Comment by danidoedel** [comment] 2017-01-09 21:12
iOS

**Comment by Alex-302** [comment] 2017-01-10 10:11
It seems that $generichide rules are not working as expected.
https://github.com/AdguardTeam/AdguardForiOS/issues/255

**Comment by JonasNo** [comment] 2017-04-27 04:18
windowscentral use two inline heuristics scripts. When the number of blocked stuff gets over a specific value the anti-adblocker nag shows, sometimes after a delay. "Mouse there is cat, run!"

**Comment by Alex-302** [comment] 2017-04-27 13:55
@JonasNo Is this issue reproducible on your side? I can't reproduce.

**Comment by ghajini** [comment] 2017-07-15 17:54
hi @Alex-302 
some breakage reported....
clicking top left corner as shown in ss doesn't expand menu
![chrome_2017-07-15_23-15-53](https://user-images.githubusercontent.com/20338483/28241571-bedfd58e-69b4-11e7-996c-1929aa080ec7.png)

windowscentral.com

**Comment by Alex-302** [comment] 2017-07-17 11:45
Fixed

**Closed by Alex-302** 2017-07-17 11:45 UTC
Labels: Anti Adblock Script
