### ISSUE TITLE
The rule _ad300. is blocking access to lapuelle-juridique.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#105109] opened 2021-12-30 09:12 UTC
@MlecerfAxe commented on [Tue Dec 21 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1931)

### Issue Details

- **AdGuard version:**
  - Version 3.6.16
- **Browser and version:**
  - Chrome Version 96.0.4664.45 
- **Operating system and version:**
  - Windows 10 & Linux Mint & Ubuntu
- **Filters you use in AdGuard:**
  - Base filter
- **Stealth Mode settings:**
  - it's disabled
- **Other browser extensions:**
  - 

### Expected Behavior

My site page should display

### Actual Behavior

The page does not appear and it tells me that I am not connected to the internet however all the other pages of my site are working, I only have one problematic page and it ends with "_ad300.html "

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot](https://user-images.githubusercontent.com/96476274/146926221-356a9796-91fd-4a06-92d2-49b059176219.png)

</details>

### Additional Information

---

@Birbber commented on [Wed Dec 22 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1931#issuecomment-999427769)

@MlecerfAxe Could you send us the link, so we could check it on our end?

---

@MlecerfAxe commented on [Fri Dec 24 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1931#issuecomment-1000728201)

@Birbber [https://www.lapuelle-juridique.com/l-administration-saisie-d-une-demande-de-rupture-conventionelle-est-ellle-en-obligation-de-mener-la-procedure-a-son-terme---_ad300.html](https://www.lapuelle-juridique.com/l-administration-saisie-d-une-demande-de-rupture-conventionelle-est-ellle-en-obligation-de-mener-la-procedure-a-son-terme---_ad300.html)

---

@Birbber commented on [Fri Dec 24 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1931#issuecomment-1000768756)

@MlecerfAxe This website won't load even without AdGuard extension, giving a message in console: https://uploads.adguard.com/annrgy_k9b9d.png

---

@MlecerfAxe commented on [Wed Dec 29 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1931#issuecomment-1002648050)

@Birbber We use certain country ip blocking, can you tell me which country you are doing your tests from and can you provide me with a fixed ip that i can see to allow it

---

@Aydinv13 commented on [Wed Dec 29 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1931#issuecomment-1002738848)

@Birbber I can confirm the issue, the rule `_ad300.` is blocking access to the website (base filter)

**Comment by zloyden** [comment] 2021-12-30 09:30
@MlecerfAxe that was caused by the rule from the `Easylist` and it was fixed by the author of the filter. It should be fine in next filter update.

**Closed by zloyden** 2021-12-30 09:30 UTC
