### ISSUE TITLE
 http://www.bloomberg.com - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2331] opened 2016-06-16 20:57 UTC
http://www.bloomberg.com
![image](https://cloud.githubusercontent.com/assets/15856304/16132927/fb81a616-341d-11e6-9cc2-1351d7ec7bd8.png)

only mac, both app and extension, doesn't appear on win

**Comment by Alex-302** [comment] 2016-06-17 11:20
Which browser?

**Comment by evgeniy-ADG** [comment] 2016-06-17 11:30
Safari, I think.

**Comment by vozersky** [comment] 2016-06-17 11:57
Managed to reproduce it on mac, Chrome only, Safari is clear.

**Comment by evgeniy-ADG** [comment] 2016-06-17 12:04
Да, кхром, сорри. Не я тестил.

**Comment by Alex-302** [comment] 2016-06-20 09:57
Не могу поймать, видать редкое явление.

**Comment by Aokromes** [comment] 2016-08-07 20:46
I have this issue on windows with opera.

**Comment by Alex-302** [comment] 2016-08-08 09:53
@Aokromes nothing on my end.
Does it appears only once?

**Comment by Aokromes** [comment] 2016-08-08 10:47
I see it from time to time.

**Comment by Alex-302** [comment] 2016-08-08 13:13
I can't reproduce it. Could yo please make a screenshot of html code of this message?

**Comment by Aokromes** [comment] 2016-08-08 13:29
http://i.imgur.com/qGe8xrp.png

**Comment by Aokromes** [comment] 2016-08-09 11:11
http://i.imgur.com/VfxECiJ.png

**Comment by Alex-302** [comment] 2016-08-09 16:54
Please try:
```
bloomberg.com###adBlockerContainer
```
and make a screenshot of overlay code(is is not transparent, as I see on screenshot above)

**Comment by Aokromes** [comment] 2016-08-09 17:04
It looks to work:
http://i.imgur.com/Ey0ieke.png

**Comment by Alex-302** [comment] 2016-08-09 17:46
Is my rule works correctly? No overlay here?

**Comment by Aokromes** [comment] 2016-08-09 18:08
It looks so, i don't see any word of anti-adblock on any browser.
BTW. that adgurd thing is intended typo?

**Comment by Alex-302** [comment] 2016-08-10 08:04
Added to Annoyances filter
```
bloomberg.com###adBlockerContainer
```
> BTW. that adgurd thing is intended typo?

where did you see it?

**Comment by Aokromes** [comment] 2016-08-10 08:16
at http://i.imgur.com/Ey0ieke.png look the selected row and under it.

**Comment by Alex-302** [comment] 2016-08-10 08:32
)) It will be fixed with a new Assistant.

**Closed by Alex-302** 2016-08-10 08:32 UTC
Labels: Anti Adblock Script, MacOS App
