### ISSUE TITLE
tutcourse.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100851] opened 2021-11-22 08:34 UTC
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://tutcourse.co/home-v2/#gsc.tab=0`

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/142828662-5655aae0-e956-4f7e-a1d3-e41b58d9b069.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment] 2021-11-24 03:24
`tutcourse.com##.stream-item-widget` from uBlock Filters seem to work for this.

**Comment by AdamWr** [comment] 2021-11-25 10:18
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/99760

**Closed by AdamWr** 2021-11-25 10:18 UTC
Labels: Unsorted

**Comment by chirag127** [comment] 2021-11-26 12:48
> `tutcourse.com##.stream-item-widget` from uBlock Filters seem to work for this.

I had once thought of using ublock filters but seems not it's not my cake , they seemed to whitelist ghide for too many sites ( more than 1800-1900 sites ) and many times not fix the issues because of whitelisting the ghide .
