### ISSUE TITLE
www.geektonight.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99775] opened 2021-11-12 12:34 UTC
**Issue URL (Ads/Annoyance)**:  `https://www.geektonight.com/best-udemy-data-science-course/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141467832-e08b74e9-6495-4cc1-aab9-acf69f178269.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-11-12 12:37
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/99736

**Closed by AdamWr** 2021-11-12 12:37 UTC
