### ISSUE TITLE
wp.pl - ad leftover

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5579] opened 2017-07-06 21:55 UTC
***Description***:
There are ads on https://www.wp.pl/
Reproduced on our side

<details><summary>Screenshot:</summary>

![screen shot 2017-07-07 at 12 48 37 am](https://user-images.githubusercontent.com/28784344/27934383-221d6c14-62ae-11e7-9cd5-774604517b1a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS  
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 11, 14, 216, 217
Ticket ID (if exists): | 1570768

**Comment by AdamWr** [comment] 2017-07-09 20:47
It is duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/5564

**Closed by AdamWr** 2017-07-09 20:47 UTC
