### ISSUE TITLE
vidcloud9.com

### ISSUE THREAD

**Issue by gaveer** [AdguardTeam/AdguardFilters#50633] opened 2020-02-28 10:14 UTC
### Problem Description
Video are not played when i turn the AdGuard on on vidcloud9.com site
### Proposed Solution
add new rule to the filter : 
@@||cdnfile.info^$domain=vidcloud9.com
### Alternatives Considered
@@||hls26s.cdnfile.info/serverus_new/stream/*$domain=vidcloud9.com
@@||cdnfile.info^$domain=vidcloud9.com
### Additional Information
https://vidcloud9.com/videos/desus-mero-season-2-episode-8
try to play this video and you see it give you error of not playing 
![image](https://user-images.githubusercontent.com/45834601/75539853-9ba72880-5a23-11ea-8119-b07e7395e620.png)

**Comment by AdamWr** [comment] 2020-02-28 11:12
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/50634

**Closed by AdamWr** 2020-02-28 11:12 UTC
