### ISSUE TITLE
codeburst.io

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100979] opened 2021-11-23 12:44 UTC
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://codeburst.io/7-vs-code-extensions-that-i-cant-live-without-765eeae3fcbf`

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/143025817-4e418e12-c965-4404-845e-13ac999047e3.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment] 2021-12-03 15:11
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/100759

**Closed by AdamWr** 2021-12-03 15:11 UTC
Labels: Unsorted
