### ISSUE TITLE
freetutsdownload.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92542] opened 2021-08-26 09:30 UTC
**Issue URL (Anti Adblock Script):**https://freetutsdownload.net/home/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130938002-3f298acb-7eba-4dbc-b8f4-875239328841.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-09-08 08:04
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/92292

**Closed by AdamWr** 2021-09-08 08:04 UTC
