### ISSUE TITLE
streamingsites.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#95121] opened 2021-09-18 13:40 UTC
**Issue URL (Ads)** : https://streamingsites.com/
https://streamingsites.com/free-movies-streaming-sites/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133900993-40d853fc-a7df-46ef-933b-bd46417fe06d.png)
![image](https://user-images.githubusercontent.com/76880977/133901143-41d405e6-cab4-4d0a-a92b-a1b9844b2dab.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-10-06 08:34
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/94433

**Closed by AdamWr** 2021-10-06 08:34 UTC
