### ISSUE TITLE
unionpeer.org incorrect blocking

### ISSUE THREAD

**Issue by odudnyk** [AdguardTeam/AdguardFilters#3509] opened 2016-11-22 07:26 UTC
**Mobile filters cutting out templates after update**:

After updating filters on Android, templates of some websites are cutting out 
<details>

customer id: 1452603

![image](https://cloud.githubusercontent.com/assets/23573691/20514573/545c171e-b095-11e6-937a-9abda6785614.png)

![image](https://cloud.githubusercontent.com/assets/23573691/20514616/ab62c7ec-b095-11e6-8dbc-97bae547a4da.png)

{
  "advancedPreferences" : {
    "pref.vpn.disable.pause" : false,
    "pref.har.capture" : false,
    "pref.vpn.ipv6.force" : false,
    "pref.vpn.ipv4.force.default" : false,
    "pref.proxy.block.ipv6" : false,
    "pref.splash.enabled" : true,
    "pref.vpn.ipv6.disable" : false,
    "pref.vpn.capture" : false,
    "pref.vpn.ipv4.force.complex" : false,
    "pref.vpn.ipv6.bypass" : false
  },
  "androidVersion" : "6.0.1 (sdk=23)",
  "appLanguage" : "ru",
  "applicationId" : "133eafc570b2d5dc",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "LGE Nexus 5",
  "deviceSpeedRank" : 165,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 14, 1, 211 ],
  "environment" : "release",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "LOW_PRIORITY",
  "installedPackages" : [ "ru.stellio.player_unlocker;version=4.01;system=false", "com.google.android.youtube;version=11.43.54;system=true", "com.android.providers.telephony;version=6.0.1;system=true", "com.google.android.gallery3d;version=1.1.40301;system=true", "com.google.android.googlequicksearchbox;version=6.8.21.21.arm;system=true", "com.android.providers.calendar;version=6.0.1;system=true", "com.alibaba.aliexpresshd;version=5.0.8;system=false", "com.android.providers.media;version=6.0.1;system=true", "com.google.android.apps.docs.editors.docs;version=1.6.442.18.35;system=true", "com.google.android.onetimeinitializer;version=6.0.1;system=true", "com.shazam.android;version=7.2.2-161114;system=false", "com.qualcomm.shutdownlistner;version=6.0.1;system=true", "cc.pacer.androidapp;version=p2.15.5;system=false", "com.android.wallpapercropper;version=6.0.1;system=true", "ru.djaz.tv;version=1.5.8;system=false", "com.android.documentsui;version=6.0.1;system=true", "ru.droidlab.bogrpro;version=1.120;system=false", "com.android.externalstorage;version=6.0.1;system=true", "com.google.android.apps.enterprise.dmagent;version=6.81;system=true", "com.android.htmlviewer;version=6.0.1;system=true", "com.whatsapp;version=2.16.352;system=false", "com.android.mms.service;version=6.0.1;system=true", "com.google.android.apps.docs.editors.sheets;version=1.6.442.04.35;system=true", "com.google.android.apps.docs.editors.slides;version=1.6.442.04.35;system=true", "com.android.providers.downloads;version=6.0.1;system=true", "com.android.phasebeamorange;version=1.0;system=true", "ru.mts.mymts;version=4.0.0;system=false", "ru.ulmart.mobapp;version=1.10.5;system=false", "com.google.android.apps.messaging;version=2.0.069 (3402275-38.phone);system=true", "tunein.player;version=17.0.1;system=false", "com.keramidas.TitaniumBackup;version=7.3.0.2;system=false", "com.google.android.apps.genie.geniewidget;version=2.8.5 (136063537);system=true", "ru.ntv.client;version=4.2.1;system=false", "com.google.android.configupdater;version=6.0.1;system=true", "org.geometerplus.zlibrary.ui.android;version=2.7.8;system=false", "ru.stellio.player;version=4.921;system=false", "com.jrzheng.supervpnfree;version=2.0.1;system=false", "com.android.defcontainer;version=6.0.1;system=true", "ru.stellio.player.skin.flat;version=1.04;system=false", "com.android.providers.downloads.ui;version=6.0.1;system=true", "com.android.vending;version=7.1.15.I-all [0] [PR] 137333487;system=true", "com.android.pacprocessor;version=6.0.1;system=true", "com.lge.SprintHiddenMenu;version=6.0-PDK2146991;system=true", "com.android.certinstaller;version=6.0.1;system=true", "com.android.carrierconfig;version=1.0.0;system=true", "com.google.android.marvin.talkback;version=5.0.4;system=true", "android;version=6.0.1;system=true", "com.lge.update;version=6.0.1;system=true", "com.google.android.apps.inputmethod.hindi;version=2.3.1.100257128-preload-armeabi-v7a;system=true", "com.android.nfc;version=6.0.1;system=true", "com.android.stk;version=6.0.1;system=true", "com.android.backupconfirm;version=6.0.1;system=true", "p.jasi2169.butorrent;version=1.2;system=false", "com.google.android.launcher;version=1.3.large;system=true", "com.google.android.deskclock;version=4.6.1 (3299599);system=true", "com.android.statementservice;version=1.0;system=true", "com.google.android.gm;version=6.10.23.137993986.release;system=true", "ru.yandex.rasp;version=3.22;system=false", "com.webmoney.my;version=2.7.6, build 8b64627;system=false", "com.google.android.setupwizard;version=2.0;system=true", "com.qualcomm.qcrilmsgtunnel;version=6.0.1;system=true", "com.android.providers.settings;version=6.0.1;system=true", "com.android.sharedstoragebackup;version=6.0.1;system=true", "com.google.android.music;version=7.0.4007-1.J.3489099;system=true", "com.android.printspooler;version=1;system=true", "com.android.dreams.basic;version=6.0.1;system=true", "ru.sportmaster.app;version=1.0;system=false", "com.android.inputdevices;version=6.0.1;system=true", "com.redbend.vdmc;version=4.5.1.10;system=true", "com.google.android.dialer;version=4.2.136732862;system=true", "com.socialnmobile.dictapps.notepad.color.note;version=3.11.7;system=false", "com.adguard.android;version=2.7.220;system=false", "com.google.android.apps.cloudprint;version=1.36b;system=true", "com.android.musicfx;version=1.4;system=true", "com.google.android.apps.docs;version=2.4.382.19.35;system=true", "com.google.android.apps.maps;version=9.41.1;system=true", "com.google.android.apps.plus;version=9.1.0.138578129;system=true", "com.android.cellbroadcastreceiver;version=6.0.1;system=true", "com.google.android.webview;version=54.0.2840.85;system=true", "com.quickoffice.android;version=6.5.1.12;system=false", "com.opera.browser;version=37.0.2192.105088;system=false", "com.google.android.contacts;version=1.5.16;system=true", "com.google.android.apps.fitness;version=1.62.06-108;system=true", "com.android.server.telecom;version=6.0.1;system=true", "com.google.android.syncadapters.contacts;version=6.0.1;system=true", "com.android.facelock;version=6.0.1;system=true", "com.android.keychain;version=6.0.1;system=true", "com.google.android.gm.exchange;version=6.4.123892212.release;system=true", "com.google.android.calculator;version=7.1.1 (3300836);system=true", "com.android.chrome;version=54.0.2840.85;system=true", "com.google.android.packageinstaller;version=6.0.1;system=true", "com.google.android.street;version=2.0.0.137864541;system=false", "com.google.android.gms;version=10.0.84 (438-137749526);system=true", "com.google.android.gsf;version=6.0.1;system=true", "com.google.android.tag;version=1.1;system=true", "com.google.android.tts;version=3.10.10;system=true", "com.google.android.apps.walletnfcrel;version=1.0.103778191;system=true", "com.android.calllogbackup;version=6.0.1;system=true", "com.google.android.partnersetup;version=6.0.1;system=true", "com.google.android.videos;version=3.20.10;system=true", "com.android.proxyhandler;version=6.0.1;system=true", "com.google.android.feedback;version=6.0.1;system=true", "com.google.android.apps.photos;version=2.4.0.138833446;system=true", "com.google.android.calendar;version=5.6.6-137495241-release;system=true", "com.android.managedprovisioning;version=6.0.1;system=true", "ru.yandex.metro;version=2.4.3;system=false", "com.bittorrent.client;version=3.28;system=false", "com.kaspersky.qrscanner;version=1.1.0.228;system=false", "com.android.providers.partnerbookmarks;version=6.0.1;system=true", "com.google.android.gsf.login;version=6.0.1;system=true", "com.valvesoftware.android.steam.community;version=2.1.6;system=false", "com.android.wallpaper.livepicker;version=6.0.1;system=true", "com.google.android.voicesearch;version=2.1.4;system=false", "com.adobe.air;version=23.0.0.257;system=false", "com.google.android.inputmethod.korean;version=1.3.1.98367236-preload-armeabi-v7a;system=true", "com.google.android.apps.translate;version=5.5.0.RC04.137189260;system=false", "com.adobe.reader;version=16.4;system=false", "com.google.android.backuptransport;version=6.0.1;system=true", "com.android.settings;version=6.0.1;system=true", "com.google.android.inputmethod.pinyin;version=4.1.2.98367006-preload-armeabi-v7a;system=true", "com.google.android.apps.books;version=3.10.29;system=true", "pl.solidexplorer2;version=2.2.3;system=false", "com.android.vpndialogs;version=6.0.1;system=true", "com.google.android.ears;version=1.2.0;system=true", "com.google.android.keep;version=3.3.431.0;system=true", "com.google.android.talk;version=14.0.136618992;system=true", "pl.solidexplorer.unlocker;version=1.2;system=false", "eu.chainfire.supersu;version=2.78;system=false", "com.android.phone;version=6.0.1;system=true", "com.android.shell;version=6.0.1;system=true", "com.android.providers.userdictionary;version=6.0.1;system=true", "jp.co.omronsoft.iwnnime.ml;version=2.2.6.jp-Google-T-21;system=true", "com.android.location.fused;version=6.0.1;system=true", "com.android.systemui;version=6.0.1;system=true", "com.android.bluetoothmidiservice;version=6.0.1;system=true", "com.kmplayerpro;version=1.1.7;system=false", "ru.ideast.championat;version=4.1.9;system=false", "ru.stellio.player.skin.material;version=1.91;system=false", "com.google.android.play.games;version=3.9.08 (3448271-038);system=true", "pl.solidexplorer.plugins.ftpserver;version=1.2.2;system=false", "com.google.android.apps.magazines;version=4.0.0;system=true", "com.google.android.apps.gcs;version=D.1.5.14 (3327632);system=true", "com.android.bluetooth;version=6.0.1;system=true", "com.qualcomm.timeservice;version=6.0.1;system=true", "com.android.providers.contacts;version=6.0.1;system=true", "com.android.captiveportallogin;version=6.0.1;system=true", "com.droid27.transparentclockweather;version=0.91.07.06;system=false", "com.google.android.GoogleCamera;version=3.2.045 (2821762-30);system=true", "com.hp.android.printservice;version=2.14-2.1.2-12b-16.3.15-102;system=false", "com.google.android.inputmethod.latin;version=5.1.23.127065177-armeabi-v7a;system=true" ],
  "installerPackage" : null,
  "kernelVersion" : "3.4.0-g99666f7",
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "referrer" : null,
  "sendAnonymousStatistics" : false,
  "showUsefulAds" : false,
  "sourceApk" : "/data/app/com.adguard.android-1/base.apk",
  "sslMitmConfiguration" : null,
  "statisticsInfo" : "Blocked threats:3; Blocked banners:726689; Traffic saved:18982953984;",
  "trial" : false,
  "updateChannel" : "RELEASE",
  "upstreamProxySettings" : null,
  "userfilter" : [ "et-code.ru" ],
  "versionName" : "2.7.220",
  "whitelist" : [ ]
}>

**Comment by vgavrish** [comment] 2016-11-22 09:58
есть пока такой лог 
не прорисовывает,даже обычную домашнюю страницу Яндекс или новости там проверьте,так как когда отключают программу то все нормально грузится. 10-40 по времени
[debug (1).txt](https://github.com/AdguardTeam/AdguardFilters/files/606005/debug.1.txt)

**Comment by vgavrish** [comment] 2016-11-22 10:01
12:55 с мобильным 
[debug (2).txt](https://github.com/AdguardTeam/AdguardFilters/files/606007/debug.2.txt)

**Comment by vozersky** [comment] 2016-11-22 10:04
@Alex-302 could you please check this? can't reproduce on my side though

**Comment by Alex-302** [comment] 2016-11-22 12:10
Not reproduced.
try
```
@@||unionpeer.org^$content
```

**Comment by ameshkov** [comment] 2016-11-22 12:30
Caused by this issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/921

Will be resolved in v2.8

**Closed** 2017-07-15 18:19 UTC
Labels: Incorrect Blocking
