### ISSUE TITLE
web page broken

### ISSUE THREAD

**Issue by xnusnim** [AdguardTeam/AdguardFilters#169824] opened 2024-01-03 05:01 UTC
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Safari

### AdGuard version

version 1.11.16 (build 324, CT 2.0.44)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://honkailab.com

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

It was infected with adshield and only breakage when I turned on adguard for safari, but I made exceptions to a few filters and it worked normally. So it seems there is a problem with the four domains below.

<hr>
||html-load.com^$popup <br>
||content-laoder.com^$popup<br>
||css-load.com^$popup<br>
||07c225f3.online^$popup<br>
<hr>

## User filter <br>
@@||html-load.com^$popup <br>
@@||content-laoder.com^$popup<br>
@@||css-load.com^$popup<br>
@@||07c225f3.online^$popup<br>
<hr>

## Before applying user filters
https://github.com/AdguardTeam/AdguardFilters/assets/81290656/f3061f18-bb9d-4454-965d-b7219074face

## after applying user filters
https://github.com/AdguardTeam/AdguardFilters/assets/81290656/791c7fb3-74e6-4b71-9012-6dfa5fb63846

### Privacy

- [X] I agree to follow this condition

**Comment by xnusnim** [comment] 2024-01-03 05:05
Error Occurrence Conditions
- After activating adguard, wait 15 to 20 seconds while refreshing the website. Then the web page is breakage.(Only Safari)
- OS : MAC
- Browser : safari
- adblock : adguard for safari

**Comment by piquark6046** [comment] 2024-01-03 07:43
`$popup` modifier does not block any request in a webpage.
It closes a browser tab that the visited URL is matched.

To resolve your issue, please install [microShield](https://community.list-kr.com/docs/AdGuard/Userscripts/microShield).

**Comment by piquark6046** [comment] 2024-01-03 07:43
Duplicate of #166433

**Closed by piquark6046** 2024-01-03 07:43 UTC
Labels: Unsorted
