### ISSUE TITLE
dl.freetutsdownload.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99844] opened 2021-11-12 15:31 UTC
**Issue URL (Annoyance)**:

https://dl.freetutsdownload.net/redirect-to/?url=https%3A%2F%2Fchiasefontt-my.sharepoint.com%2F%3Af%3A%2Fg%2Fpersonal%2Fkpdvbguchmfk_chiasefontt_onmicrosoft_com%2FEqTeB4kThTVCsEFU4veB8cwBMm1t6SkVVSpzrAYIx9b7Mg%3Fe%3DmXzRx1
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141491774-29f5017e-2380-4b7f-976a-043c5dbefabb.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-11-12 15:34
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/94442

**Closed by AdamWr** 2021-11-12 15:34 UTC
