### ISSUE TITLE
my.xfinity.com - Adg blocks videos

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4828] opened 2017-04-19 19:48 UTC
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
>When Adguard is on, videos on my Comcast homepage (news &
entertainment clips) will not play. 

The user reproduced the issue and sent us the screenshots of Blocked elements in Adguard Filtering log:

Screenshots:
<details>

<img width="1440" alt="screen shot 2017-04-19 at 6 35 35 am" src="https://cloud.githubusercontent.com/assets/22892774/25198630/d8ddfd7e-2550-11e7-96a8-d5d8ab53218d.png">

</details>

<details>

<img width="1440" alt="screen shot 2017-04-19 at 6 42 23 am" src="https://cloud.githubusercontent.com/assets/22892774/25198639/dd8d3c90-2550-11e7-8b7c-e24bdea33a4d.png">

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Adguard version: | 1.4.1
Adguard filters: | 2 3 10

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1543184

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment] 2017-04-20 11:36
Try this rule:
```
@@||comcastcom.*.omtrdc.net/b/ss/
```

**Comment by Bohdan-SUP** [comment] 2017-04-21 11:33
> No that didn't work. Same issue.
Anything else we can try?

**Comment by Alex-302** [comment] 2017-04-21 13:13
Another try:
```
@@||dpm.demdex.net/id$domain=xfinity.com
```
Check it without and with previous rule.

**Comment by Bohdan-SUP** [comment] 2017-04-21 14:15
Emailed the user, will update.

**Comment by Alex-302** [comment] 2017-04-24 14:27
@Michael23456 hi. Is it possible to check this site remotely via TeamViever?(Can be checked in a virtual machine also). If "Yes", please write me to Skype - `alxbrv`

![image](http://i91.fastpic.ru/big/2017/0424/c6/4e4ab7b4a2d0080b37e87213465413c6.jpg)

**Comment by evgeniy-ADG** [comment] 2017-04-24 14:29
@Alex-302  We were discussing the issue on skype a couple of days ago, we have a huge time difference so if it's convenient for you to do a TV session at 8 am we can try to schedule it again.

**Comment by Alex-302** [comment] 2017-04-25 09:24
Only at 8 am? I can't at this time, because I am not near PC at this time. I can at 10:00AM to 01:00AM

**Comment by Alex-302** [comment] 2017-04-25 09:58
Is it is works, when spyware filter is disabled?
Asked user from USA(he uses Windows), the issue was not reproduced.

**Comment by evgeniy-ADG** [comment] 2017-04-25 10:13
It's too late for the customer, 8 am Kyiv timezone is the only option. Will ask about the spyware filter.

**Comment by zebrum** [comment] 2017-04-26 13:07
did not work either.

**Comment by Alex-302** [comment] 2017-04-26 14:05
Then user should try to disable filters one-by-one and find a filter, which causes this issue. After that I will try to make specific rule.

**Comment by KozelElena** [comment] 2017-06-06 21:06
The user has tried it with and without each filter with the same result. Nothing is working so far. (The user tried Ad Block Plus - it doesn't work either)

**Comment by Alex-302** [comment] 2017-06-07 12:39
I can't to fix it without access to the site.
Another try:
```
@@||xfinity.com^$urlblock
```

**Comment by KozelElena** [comment] 2017-06-23 22:37
We've got another complaint about this website (1578673), suggested the rule above. Waiting for reply

**Comment by KozelElena** [comment] 2017-06-24 23:01
Got an answer: "Tried your fix and the videos now play, however all the ads play also. This looks like one half of a fix."

Is there anything else we can suggest?

**Comment by Alex-302** [comment] 2017-06-26 09:01
That rule for test only.
I need remote access to PC with the issue.

**Comment by dzamyshlyayeva** [comment] 2017-06-28 01:42
asked for a tv. waiting for his response

**Comment by vmalyuta** [comment] 2017-06-29 09:34
user didn't agree for TV

**Comment by Alex-302** [comment] 2017-06-29 09:40
Ok then. It was checked by another user in USA, the issue is not confirmed.

**Closed by Alex-302** 2017-06-29 09:40 UTC
Labels: MacOS App, Question
