### ISSUE TITLE
Issue URL (Anti Adblock Script)

### ISSUE THREAD

**Issue by Himike2345** [AdguardTeam/AdguardFilters#180236] opened 2024-05-28 03:51 UTC
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac, Other ad blocker

### AdGuard version

4.3.46

### What type of problem have you encountered?

Website or app doesn't work properly, AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://decrypt.day/app/id6475033368#download-box

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Other

AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Self-destruction of third-party cookies, Disable cache for third-party requests, Hide Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

1. <comment>
User: @mikeaotrinh
Click on blue button Download
2. Screenshots
<details><summary>Screenshot 1:</summar
<img width="1440" alt="111" src="https://github.com/AdguardTeam/AdguardFilters/assets/170998019/3d54cd8f-07ca-446a-a3c7-a17655b7240c">
y>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment] 2024-05-28 07:47
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/173859

**Closed by Alex-302** 2024-05-28 07:47 UTC
Labels: A: In progress, A: Invalid, Unsorted
