### ISSUE TITLE
udemycourses.me

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99918] opened 2021-11-13 04:00 UTC
**Issue URL (Ads/Annoyance)**:  `https://udemycourses.me/google-drive-ultimate-course-2021-free-ddownload/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141604840-9f06d705-483a-4ef6-806c-1107eead91c8.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by AdamWr** [comment] 2021-11-26 09:26
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/99790

**Closed by AdamWr** 2021-11-26 09:26 UTC
Labels: P4: Low
