### ISSUE TITLE
Allocine app- Incorrect Blocking - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6505] opened 2017-08-27 20:49 UTC
***Description***:
* **Current behaviour**: 

When Adguard enabled - the app AlloCine on Android does not show the trailer
https://play.google.com/store/apps/details?id=com.allocine.androidapp&hl=en

when disabled- it`s working
reproduced on our side
<details><summary>Screenshot:</summary>

![screenshot_2017-08-25-23-44-26](https://user-images.githubusercontent.com/28784344/29753795-c1154822-8b81-11e7-849e-7de4db0e562a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.136
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 
Adguard filters: | 1,2,3,4,11,14,16
Ticket ID (if exists): | 1618663

**Comment by Alex-302** [comment] 2017-08-28 09:31
I can't reproduce. Which filter causes it?

**Comment by veronikasav** [comment] 2017-09-22 11:23
Asked the user to specify whether the issue still persists.

**Comment by darkulish** [comment] 2017-09-23 14:02
customer says the issue still persists, mobile ads filter causes the issue

**Comment by Alex-302** [comment] 2017-09-24 14:23
Ask to disable all filters except `mobile`, then close this app, and collect HTTP(web requests) log with time stamp.

**Comment by Alex-302** [comment] 2017-09-24 14:24
@AdamWr please check on your device.

**Comment by AdamWr** [comment] 2017-09-29 11:35
I can reproduce.
Added to Mobile filter:
`@@||imasdk.googleapis.com/native/core/*/native_bridge__*.js$app=com.allocine.androidapp`

**Closed by AdamWr** 2017-09-29 11:35 UTC
Labels: Android, Cannot Reproduce, Incorrect Blocking
