### ISSUE TITLE
techashi.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93061] opened 2021-08-30 17:00 UTC
**Issue URL (Annoyance)**:https://techashi.com/2021/04/09/the-advanced-javascript-concepts-2021-udemy-free-download-2/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131376421-e9ac4aa3-e00a-457e-9dec-6a802c58f9a7.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-08-30 18:01
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/92290

**Closed by AdamWr** 2021-08-30 18:01 UTC
