### ISSUE TITLE
AdGuard breaks Google search in Firefox on macOS

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#37382] opened 2019-07-24 07:46 UTC
> When doing a Google search in Firefox, with AdGuard running, a click on the search results will do nothing. However do the same search on Chrome or Safari, and there are no problems, the click thru happens fine. There’s something about AdGuard with Firefox that won’t process the link click

> It’s the Adguard Tracking Protection Filter (2.0.8.5) that’s causing the issues. This rule here is triggered. This is just a search for ‘dogs’ and then click on the first result. Google search sends back an xmlhttprequest, but because it's getting blocked, it sometimes doesn’t execute the click. Disable the filter rules and it works fine. Only happens on firefox for some reason.

```
Request URL
https://www.google.com/gen_204?atyp=i&ei=l242XebhHY6_3LUPvOe62A0&ct=slh&v=2&s=3&pv=0.4393284392533766&me=33:1563848347187,V,0,0,0,0:7864,U,7864:1,V,0,0,1317,718:298,h,1,CAUQAA,i:342,G,1,CAUQAA,32,6,1:0,c,198,178:2,G,1,CAUQAA,32,6:2,e,C&zx=1563848355698

Status
Request blocked.

Source URL
https://www.google.com/

Application
Firefox

Rules
||google.*/gen_204?$~xmlhttprequest (AdGuard Tracking Protection filter)

Data type
Other

Destination address
216.58.200.100:443

Connection ID
1000010

Request ID
235379

```

For more information and logs, check the following ID: 2227951

**Comment by krystian3w** [comment] 2019-07-24 09:54
On Windows filter no break Google.

**Comment by Alex-302** [comment] 2019-07-24 12:10
I can't reproduce on mac.
@slavaleleka please take a look.

**Comment by Alex-302** [comment] 2019-07-24 12:10
@Eugene-Savenko please ask user to sent report from AdGuard and attach report link here.

**Comment by slavaleleka** [comment] 2019-07-24 15:38
I also can't reproduce it

**Comment by Eugene-Savenko** [comment] 2019-07-26 12:09
@Alex-302 which report? Do you need state.txt or something else? Please, open this ticket in CRM for more info: 2227951 (!!!)

**Comment by Alex-302** [comment] 2019-07-27 20:14
@Alex-302 report from AdGuard:) I need all AG settings. Log is useless here.

**Comment by Eugene-Savenko** [comment] 2019-07-30 09:13
Okay. Meanwhile, we have another report from 2244067:

> Hello, I am on Adguard for iMac ver 2.0.6.559 and I have a problem with Firefox Browser. I get no reaction when I click a Google search result link if the AdGuard spyware filter is on. Can you please tell me which filters in the spyware filter I should turn off so I can still keep the spyware filter on while using Firefox?

**Comment by krystian3w** [comment] 2019-07-30 10:29
Maybe use this: https://reports.adguard.com/en/new_issue.html

**Comment by Eugene-Savenko** [comment] 2019-07-30 12:09
@krystian3w oh great, thanks!

**Comment by Alex-302** [comment] 2019-07-31 18:45
@Eugene-Savenko maybe user can add to user filter:
```
@@||google.*/gen_204?
```

**Comment by Eugene-Savenko** [comment] 2019-08-05 06:13
We've sent it to customers and but haven't heard back yet. Meanwhile, another one here: 1175327

> I have iMac 27” mid 2010 running High Sierra and found that, when using the latest FireFox browser the left mouse click doesn’t activate a link after doing a google search for “ux 201a radio tube” (and other searches as well) and then trying to select one of the search hits. Sometimes it will work with a double click but it is very erratic. This problem goes away when I disable adguard.

**Comment by Eugene-Savenko** [comment] 2019-08-06 07:50
From 1175327:

> Yes it now responds a lot more like it should. But the response seems slow compared to what I would expect when opening a new website.

**Comment by krystian3w** [comment] 2019-08-06 08:27
@ryanbr / @khrin and maybe @rhanajoy:

https://github.com/easylist/easylist/blob/eb694f4d3c38447ad40be02f0974a73738f8683d/easyprivacy/easyprivacy_specific.txt#L879

Maybe also afected with AdBlock / Adblock Plus on Safari (macOS):

https://adblockplus.org/ad-blocker-safari <sup>(https://apps.apple.com/us/app/adblock-plus-for-safari/id1432731683)</sup>
https://getadblock.com/safari/ <sup>(https://apps.apple.com/us/app/adblock-for-safari/id1402042596)</sup>

**Comment by ryanbr** [comment] 2019-08-06 08:47
`easyprivacy/easyprivacy_general.txt:/gen_204?$image,script`
`easyprivacy/easyprivacy_specific.txt:||google.*/gen_204?$~xmlhttprequest`

I see requests from $other and $image, if I do a simple google search. but it doesn't break things? Note these filters aren't new, possibly a filter compatibility issue on Adguard?

**Comment by ryanbr** [comment] 2019-08-06 09:03
Here is a clean up, probably won't fix the issue. but it's a little better. https://github.com/easylist/easylist/commit/8d3d1806132c6176579804e7480e482a01e8214a

**Closed** 2019-09-17 21:39 UTC
Labels: A: Cannot reproduce, A: In progress, T: Incorrect Blocking
