### ISSUE TITLE
9anime.to - Anti Adblock Script - iOS

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6431] opened 2017-08-23 08:52 UTC
***Site***: https://9anime.to/watch/new-game-dub.lmm3/39z36y
***Description***: Adblock detection on iOS.

<details>
<summary>Screenshot</summary>

![img_7167](https://user-images.githubusercontent.com/10995998/29607285-0cd7768e-87f1-11e7-82a6-d7e5240e66e6.PNG)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 11
Browser: | Safari
Adguard version: | 1.3.1(106)
Simplified filters(iOS) | Off
Adguard DNS: | None

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Mobile ads filter
Safari filte

**Comment by AdamWr** [comment] 2017-09-07 10:57
I can't reproduce, it works on my iPad.
Could you please check it again?

On Windows I noticed that icons from player are blocked, added to English filter:
`@@||p.jwpcdn.com/player/v/*/jw-icons.woff$domain=9anime.to`

**Comment by danidoedel** [comment] 2017-09-10 10:45
@AdamWr Yeah no more adblock detection, but the videos are not starting for me:

![image](https://user-images.githubusercontent.com/10995998/30248323-d994f286-9625-11e7-954d-658a35747d99.png)

**Comment by AdamWr** [comment] 2017-09-10 12:53
It works fine on my iPad.

<details><summary>Screenshot</summary>

![9a](https://user-images.githubusercontent.com/29142494/30249197-5dd4fe40-9637-11e7-868d-edad9f2a7f89.png)

</details>
<br>

Could you please disable all filters and enable them one-by-one with checking, then tell me, which filter causes this issue?

**Comment by danidoedel** [comment] 2017-09-12 15:56
@AdamWr It's the English filter causing this issue for me.

**Comment by AdamWr** [comment] 2017-09-12 17:56
I don't know which rule can cause this issue.
Could you try this:
`@@||9anime.to^$elemhide`

**Comment by AdamWr** [comment] 2017-11-07 21:42
It should be fixed now.

**Closed by AdamWr** 2017-11-07 21:42 UTC
Labels: Incorrect Blocking
