### ISSUE TITLE
xxxmom.pro [NSFW] [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#43416] opened 2019-11-03 04:35 UTC
**Site**: http://xxxmom.pro/en/xxxmomvideo/1309867.html?id=roYF0lAGpjZP4uZv45YwRmZQx4AwphZGRmAGx0BN__cc&cat=mom%20riding

**Issue**: Ad banner seen on the player. Possible pop-ups seen.

**Screenshot**: https://prnt.sc/prqz7p

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 78.0.3904.87 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.2.1	 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled (Default)

**Comment by AdamWr** [comment] 2019-11-05 13:46
This website is using the same video player as here - https://github.com/AdguardTeam/AdguardFilters/issues/43415, so fixed in this commit - https://github.com/AdguardTeam/AdguardFilters/commit/d85bc96a7d8e315660f9f43a2df9b6f20c0f3ded

I couldn't reproduce popups.

**Closed by AdamWr** 2019-11-05 13:46 UTC
Labels: A: Resolved, T: Ads
