### ISSUE TITLE
gizmodo.jp [N: Nano Adblocker] [T: Ads] [T: Anti Adblock Script]

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#59738] opened 2020-07-20 18:33 UTC
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

There is a placeholder on the front page. I propose adding `gizmodo.jp##.s-body-ad` to AdGuard Japanese Filter to remove it.

There is an uncloseable anti-adblocker message sticky on the bottom. I propose `gizmodo.jp##div[style*=" fixed; width: 10"]`.

Furthermore, there is a placeholder below the article at `https://www.gizmodo.jp/2020/07/216985.html`. I propose `gizmodo.jp##.p-recommend`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/87972400-1fdb7480-cac7-11ea-9890-0f19e6377468.png)
![image](https://user-images.githubusercontent.com/22780683/87972867-f242fb00-cac7-11ea-95f1-196880208654.png)

</details><br/>

* **Expected behaviour**: 

All things mentioned above are removed.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/87972823-dc353a80-cac7-11ea-804a-dbbbdd61f619.png)
![image](https://user-images.githubusercontent.com/22780683/87972938-10106000-cac8-11ea-8383-ea85501c33cc.png)
</details><br/>

***Steps to reproduce the problem***:

1) Browse casually around on `https://www.gizmodo.jp/`.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/87972148-b6f3fc80-cac6-11ea-9da0-d56e6bea3aef.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | May 2020 Update
Browser:                               | Chrome 84.0.4147.89 x64
AdGuard version:                       | Nano Adblocker 1.0.0.152 + Nano Defender 15.0.0.201
Filters enabled:                       | See screenshot above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment] 2020-07-21 12:12
> There is an uncloseable anti-adblocker message sticky on the bottom.

It seems it is caused by the filter, which blocks `fundingchoicesmessages.google.com`. It must be fixed in filter, which causes it.
Cannot reproduce with the filters, which are in AdGuard.

**Comment by Yuki2718** [comment] 2020-07-21 14:41
Also consider to add `/api/increment-pv$xmlhttprequest` to Spyware, this was seen in several Japanese sites though one of them I've visited for confirmation is now dead.

**Comment by DandelionSprout** [comment] 2020-07-22 00:47
It appears to be the *uBlock Filters* main list of all possible lists that has `||fundingchoicesmessages.google.com^$3p` in it, meaning I presume I should contact them about it.

**Comment by okiehsch** [comment] 2020-07-22 01:43
> it seems it is caused by the filter, which blocks fundingchoicesmessages.google.com.

https://github.com/uBlockOrigin/uAssets/commit/08958cacab69ae2682248dee8c6df063b6a707a7#commitcomment-36959525

**Closed** 2020-07-22 11:49 UTC

**Comment by DandelionSprout** [comment] 2020-07-23 19:25
After some days of back and forth, it appears that the uBO team is only applying a fix for the anti-adblock messages to their privacy-specific list, and not to their main list that is causing the banners to appear.

Just in case anyone wondered what the outcome of that discussion was.
