### ISSUE TITLE
巴哈姆特 app

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#8000] opened 2017-11-30 16:39 UTC
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

Issue URL:
for iOS:
https://itunes.apple.com/tw/app/%E5%B7%B4%E5%93%88%E5%A7%86%E7%89%B9/id479826450?l=zh&mt=8

for Android:
https://play.google.com/store/apps/details?id=tw.com.gamer.android.activecenter&hl=zh_TW

— Missed Ad

Issue Type: Ads
Comment:
Screenshot: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/MlD0QeQ.jpg)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/KttwbPa.jpg)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/PANuWz5.jpg)
</details><br/>

***Steps to reproduce the problem***:
巴哈姆特 app: A social forum app.
for iOS:
https://itunes.apple.com/tw/app/%E5%B7%B4%E5%93%88%E5%A7%86%E7%89%B9/id479826450?l=zh&mt=8

for Android:
https://play.google.com/store/apps/details?id=tw.com.gamer.android.activecenter&hl=zh_TW

Please try its Android & iOS app.
"廣告" means "advertisement".
The app inserts sponsored ads between articles.
It seems that it encrypts the ad domains, such like facebook app.
It's difficult to find the ad domains.
Maybe you can find them.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | Android/iOS
Browser:                               | ?
AdGuard version:                       | AdGuard for Android v.2.10.176 RC / AdGuard Pro for iOS v1.3.2
Filters enabled:                       | English filter, Spyware filter, Social media filter, Annoyances filter, Mobile ads filter and EasyList China filter
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default/Blacklist mode)
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default Protection, AdGuard Pro for iOS with AdGuard DNS server
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment] 2017-12-04 13:44
I can't reproduce ads on Android (I see these ads if I disable AdGuard).
This rule blocks ads on my end:
`/mobile_ad.`
On iOS I will check it later.

<details><summary>Screenshot</summary>

![bahamut](https://user-images.githubusercontent.com/29142494/33555405-8f5c1690-d900-11e7-9bc6-f04149cd4f09.png)

</details>

**Comment by lancelot-moon** [comment] 2017-12-04 13:53
Hi,
Try to visit other sections, for example, GNN 新聞, 熱門看板, 熱門手遊 and somewhere.
If you see the label "廣告", it means advertisement.

**Comment by lancelot-moon** [comment] 2017-12-04 16:01
In my AdGuard, I only see the 2 rules are touched.
https://imgur.com/a/82pxR
But there are ads.

I never see ads are blocked by rule /mobile_ad.

**Comment by AdamWr** [comment] 2017-12-04 16:16
On my end this request is blocked - `https://api.gamer.com.tw/mobile_app/ad/v2/mobile_ad.php?=` and if I unblock it, I see "sponsored ads".

<details><summary>Screenshots</summary>

![ba1](https://user-images.githubusercontent.com/29142494/33562782-71f5f236-d916-11e7-9eb6-61afac143a55.png)
![ba2](https://user-images.githubusercontent.com/29142494/33562793-74abb66e-d916-11e7-8e6b-fc39a685e6a8.png)

</details>

**Comment by lancelot-moon** [comment] 2017-12-04 16:24
I manually added your rule in my user filter.
But it's useless.
There are still sponsored ads.
https://imgur.com/a/0KFBl

**Comment by lancelot-moon** [comment] 2017-12-04 17:06
Why is you event type different with mine?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/BO73ob3.png)
</details><br/>

**Comment by lancelot-moon** [comment] 2017-12-04 23:21
Your AdGuard can catch the request URL, but that URL isn't in my filtering log.
So the sponsored ads aren't blocked in my phone.
Strange...
I use HTC U11.
Android v8.0.0.
What's your Android version?
Thanks.

**Comment by AdamWr** [comment] 2017-12-05 20:06
> What's your Android OS version?

Android 6.0

> What's your filtering log when running 巴哈姆特 app?

<details><summary>Screenshots</summary>

![screenshot_1](https://user-images.githubusercontent.com/29142494/33625005-7a1e53fa-d9f6-11e7-839a-5a4a5c0066e8.png)
![screenshot_2](https://user-images.githubusercontent.com/29142494/33625002-7980a1fa-d9f6-11e7-8b32-be01a4938369.png)
![screenshot_3](https://user-images.githubusercontent.com/29142494/33625003-799feace-d9f6-11e7-8232-8653eccca616.png)
![screenshot_4](https://user-images.githubusercontent.com/29142494/33625004-79c145fc-d9f6-11e7-938b-ca1499d751f9.png)

</details>
<br>

Maybe these ads are provided in different way at your end, so could you please make a HAR file?

**Comment by lancelot-moon** [comment] 2017-12-05 20:36
Hi,
Do you mean logs and system info?
Is HAR file in logs and system info?
This is mine.
https://app.box.com/s/znyj8jfutrc792essdi4916j0m79fj7u

Or where can I export the HAR file if the above isn't what you want?

Thanks.

**Comment by AdamWr** [comment] 2017-12-05 20:43
Hi,
Thank you, but I need different log.
You can read how to make HAR file here - https://kb.adguard.com/en/android/solving-problems/har#how-to-get-har-files

**Comment by lancelot-moon** [comment] 2017-12-05 20:51
Yes, I got it.
I searched the article on google.
https://kb.adguard.com/en/android/solving-problems/har

For your reference.
HAR file:
https://app.box.com/s/axwuihfaymwlcjk28crwd1kzhbfikx7e

Thanks.

**Comment by AdamWr** [comment] 2017-12-05 20:53
Ok, thank you.

**Comment by AdamWr** [comment] 2017-12-05 22:07
It seems that unfortunately it can not be fixed on Android 7 and above.
Here is article about that - https://blog.adguard.com/en/android-nougat-release-and-what-does-it-mean-for-adguard-users/

**Comment by lancelot-moon** [comment] 2017-12-06 04:55
Hi,
I read these in the end of the article.
> In our future plans - and that's good news for users with ROOT access - we are going to develop an algorithm that will allow to get around these restrictions, provided you have ROOT access. If you don't though, unfortunately, there is nothing that can be done.

Can that URL be caught in the filtering log if using Android v7 / v8 with root access?
I don't know if my understanding is correct.
I don't have root access in my HTC U11.
Can AdGuard team do the experiment?

Thanks.

**Comment by lancelot-moon** [comment] 2017-12-06 08:23
A Taiwanese netfriend helped to do the test.
His phone is Android v7 with root access.
But AdGuard is still unable to block ads in 巴哈姆特 app.
Does AdGuard team still not develop the algorithm that will allow to get around these restrictions for above Android v7 with root access?
Thanks.

**Comment by ameshkov** [comment] 2017-12-17 18:31
> Does AdGuard team still not develop the algorithm that will allow to get around these restrictions for Android v7/v8 with root access?

Why, it's not that hard.

All you need to do is to move AdGuard's certificate from user to system store.
You can use https://f-droid.org/wiki/index.php?title=Move_Certs!&redirect=no to do it.

**Closed by ameshkov** 2017-12-17 18:31 UTC

**Comment by lancelot-moon** [comment] 2017-12-18 14:25
Hi,
I just quoted those words from the article in AdGuard Blog.
https://goo.gl/9S7VBq

Move Certs!:
https://goo.gl/UfRqXG

You're great!
Yes, the ads in 巴哈姆特 app can be blocked after moving AdGuard Personal CA to system store.
But this method is only for Android v7/v8 with root access.

So there is no method if Android v7/v8 without root access, right?
Thanks a lot!

**Comment by ameshkov** [comment] 2018-01-02 19:43
> So there is no method if Android v7/v8 without root access, right?

Actually, there is! There is an app called "Parallel Space" -- https://play.google.com/store/apps/details?id=com.lbe.parallel.intl&hl=en. 

If you run an app inside of that "Parallel Space" app, its requests are exposed to https filtering.

However, this is just a temporary solution. With time Parallel Space will start targeting Nougat, and it will be the subject of the very same limitations.

The good news is that maybe we'll be able to do the same thing (run a cloned app) inside of AG, but we need to investigate it.

**Comment by lancelot-moon** [comment] 2018-01-03 14:52
You're so erudite!
Thanks for the great work from AdGuard team!

I don't worry that AdGuard will be better and better!
Simply, I just feel that your team can have more idea to do better for the layout of app interface.

B/R

**Comment by lancelot-moon** [comment] 2018-01-04 16:58
I tried to install "Parallel Space" app.
https://play.google.com/store/apps/details?id=com.lbe.parallel.intl&hl=zh_TW

But F-Secure SAFE for Android showed that "Parallel Space" app isn't safe...
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/3wcNEuz.png)
</details><br/>

So I removed "Parallel Space" app.

**Comment by ameshkov** [comment] 2018-01-04 17:03
Most likely that's a false positive (note that the signature is "Generic"). I refuse to believe that an app with 50M+ downloads can be unsafe and still not removed from the Play Store.
