### ISSUE TITLE
yahoo.com - iOS

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3210] opened 2016-10-17 18:30 UTC
Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19450114/c6705898-94b0-11e6-9776-924db784d2cf.png)
</details>

**Filters**
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.48 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.16 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.60 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.32 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.24 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.52 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.67.31 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.62 Enabled=YES

Customer ID **1431098**

**Comment by Alex-302** [comment] 2016-10-17 20:51
Can't reproduce in Safari.
@Bohdan-SUP Is it displayed on your end?

**Comment by dzamyshlyayeva** [comment] 2017-03-29 14:01
same issue here https://us.yahoo.com/
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/24458270/20c7b9ba-14a1-11e7-9f45-cbe8758bbf61.png)

<,details>

Application version: 1.1.5.65

Device: iPhone
Platform: iOS
OS: 10.3

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.13.13 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.18 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.17 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.22 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.77 Enabled=YES

Ticket ID 1313547

**Comment by Alex-302** [comment] 2017-03-30 11:37
> OS: 10.3

it is caused by Apple's fail. Safari contains a bug, and some rules are not applied.
When the bug will be fixed, this ad will be hidden by
```
yahoo.com##a[href^="https://beap.gemini.yahoo.com/mbclk?"][target="_blank"]
```

**Closed** 2017-07-15 16:51 UTC
Labels: Ads, Bug, iOS Browser
