### ISSUE TITLE
adyou.me [Annoyance/Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#8513] opened 2017-12-17 02:33 UTC
**Site**: http://adyou.me/vkbu

**Issue**: Remove Annoyances - Flash player out of date message window & Fake Flash Player Update/Install frame below.

**Screenshot**: https://image.prntscr.com/image/eGOqsmcESUOp3-fwn_bnLw.png

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 63.0.3239.108 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.7.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains [No user filter used | Phishing & Malware Protection Enabled] `

**Comment by clementine123** [comment] 2017-12-17 02:57
One other question guys. Is it possible to remove the small pop-up window that appears when closing the tab on this page? (and in general on any page?)

Screenshot: http://prntscr.com/hoivx3

**Comment by Alex-302** [comment] 2017-12-18 10:45
> Flash player out of date message window

I can't reproduce it.

> Is it possible to remove the small pop-up window

also not reproduced.

**Comment by Alex-302** [comment] 2017-12-18 10:45
@AdamWr please check on your end.

**Comment by AdamWr** [comment] 2017-12-18 11:29
I can't reproduce first and second issue.

**Comment by BlazDT** [comment] 2017-12-18 12:54
Not reproduce the exact message, but other messages are displayed to me.

Please try this rule:
`||hitcpm.com^$third-party,empty`

Imho we should change rule ||urldelivery.com^$third-party to ||urldelivery.com^$third-party,empty as the content still gets loaded as it is a html page.

2nd element reproduced, but so far not sure how to remove it.

**Closed** 2017-12-21 08:34 UTC
Labels: A: Cannot reproduce, A: In progress, T: Ads
