### ISSUE TITLE
answersq.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94477] opened 2021-09-12 12:24 UTC
**Issue URL (Ads/Annoyance)**:
https://answersq.com/oxford-home-study-centre-free-online-courses/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132987413-ff31e497-4597-420f-8d4f-74336f776fc3.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-09-27 09:39
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/93863

**Closed by AdamWr** 2021-09-27 09:39 UTC
