### ISSUE TITLE
Consider integrating ClearURLs rules in TrackParam (as long as syntax allows)

### ISSUE THREAD

**Issue by fourquestionmarksokay** [AdguardTeam/AdguardFilters#87267] opened 2021-07-01 15:33 UTC
### Prerequisites

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

TrackParamFilter contains the filters for removing tracking parameters (most common of them all is the Urchin/\_utm\_\* parameters). [CleanURLs](https://addons.mozilla.org/en-US/firefox/addon/clearurls/) is a Mozilla-recommended extension that is designed for a similar purpose and has a longer history (started in 2017), which means that the rules have gone through thorough revisions. The project is under GPLv3, and the rules are under LGPLv3. The current rules (at https://gitlab.com/anti-tracking/ClearURLs/rules/-/blob/master/data.json) shows that there's while there's some overlap, there's some rules ([such as for IMDB](https://gitlab.com/anti-tracking/ClearURLs/rules/-/blob/7a180c3dbd2a48aeeb1271919f6a9218b4d45354/data.json#L348)) that are missing in AdGuard's rules.

### Proposed Solution

Investigate if ClearURLs' lists are suitable for integration in AdGuard's URL Parameter Tracking rules and add them into the database. Careful scrutiny is required, for example [this filter for Mozilla (which is incompatible with the current syntax anyway)](https://gitlab.com/anti-tracking/ClearURLs/rules/-/blob/7a180c3dbd2a48aeeb1271919f6a9218b4d45354/data.json#L442) will lower the security of the user (it checks if the URL is malicious and shows a message saying to not install add-ons if the link prompts to install an add-on).

### Alternatives Considered

**Do nothing:** it's not the end of the world if the integration is unsuitable for technical or other (like freedom to change the license later) reasons, someone will just notice that there's tracking links in their favorite website, report it and then added it to the Tracking Parameters filter.

**Comment by Yuki2718** [comment] 2021-07-02 11:05
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/78286

**Closed** 2021-07-05 12:42 UTC
