### ISSUE TITLE
calculator-online.net

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99674] opened 2021-11-11 17:38 UTC
**Issue URL (Ads/Annoyance)** : `https://calculator-online.net/bmi-calculator/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141343470-2a62d9b7-09ff-409f-a4ec-6cee84fb046b.png)
![image](https://user-images.githubusercontent.com/76880977/141343472-b506d5ba-5290-4960-aedc-c6cb807fb844.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-11-22 11:36
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/99265

**Closed by AdamWr** 2021-11-22 11:36 UTC
Labels: P4: Low
