### ISSUE TITLE
https://www.overclockers.ru - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4475] opened 2017-02-26 10:11 UTC
https://www.overclockers.ru

![image](https://cloud.githubusercontent.com/assets/15856304/23338774/84cd1aba-fc1c-11e6-9a26-b3f194f060ca.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | the latest one
Adguard driver (Windows): | WFP
Adguard DNS: | Default
Stealth mode options(Windows) | No
Adguard filters: | eng rus sm annoyances spyware

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1247089

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment] 2017-02-27 12:21
not reproduced

**Comment by zebrum** [comment] 2017-03-01 10:49
@Alex-302 surf the site for a little while

**Comment by Alex-302** [comment] 2017-03-01 13:37
Still can't reproduce.

**Comment by zebrum** [comment] 2017-05-30 15:31
@evgeniy-ADG if there were no other complains, probably we should close the issue.

**Comment by Bohdan-SUP** [comment] 2017-06-06 01:48
No new complaints, closing for now.

**Closed by Bohdan-SUP** 2017-06-06 01:48 UTC
Labels: Anti Adblock Script
