### ISSUE TITLE
missed ad https://m.androidcentral.com

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5233] opened 2017-06-03 06:15 UTC
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
missed ad https://m.androidcentral.com

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)
![image](https://cloud.githubusercontent.com/assets/25711093/26751212/e8ab47e8-483c-11e7-8f24-d3cf7114a840.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | chrome
Adguard version: | 2.9.70/2.9.111
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | eng, rus, annoyance, mobile, experimental, social, spyware.
Ticket ID (if exists): | 1251189

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment] 2017-06-05 04:50
Seems to be a duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/5222, will continue in that thread

**Closed by seanl-adg** 2017-06-05 04:50 UTC
