### ISSUE TITLE
Youtube blocked on private DNS

### ISSUE THREAD

**Issue by SpotlightForBugs** [AdguardTeam/AdguardFilters#193322] opened 2024-11-20 19:11 UTC
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

latest, doesnt matter here

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

youtube.com

### Ad Blocking

AdGuard Base filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

Youtube Blocked by AdGuard DNS

See https://github.com/hagezi/dns-blocklists/issues/4392

![image](https://github.com/user-attachments/assets/4d7db5aa-7b6a-405a-b7af-be0cf4450c57)

### Privacy

- [X] I agree to follow this condition

**Comment by hagezi** [comment] 2024-11-21 08:14
It is fixed.

**Comment by zloyden** [comment] 2024-11-21 09:45
> Youtube Blocked by AdGuard DNS

It's not related to the filters and we do not block YouTube. It was caused by the third-party DNS filter [as you mentioned](https://github.com/hagezi/dns-blocklists/issues/4392) and it's been fixed by `@hagezi`.

**Closed by zloyden** 2024-11-21 09:45 UTC
Labels: A: In progress, Unsorted
