### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by szyha** [AdguardTeam/AdguardFilters#132331] opened 2022-10-16 13:57 UTC
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.44.4

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://shinden.pl/episode/59474-youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-2nd-season/view/212737?r307=1#

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList, EasyPrivacy, Fanboy's Annoyances, Peter Lowe's Blocklist, Online Malicious URL Blocklist, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish Social Filters, KAD - Anti-Scam, Polish Annoyances Filters, Polish Anti Adblock Filters, Polish Anti-Annoying Special Supplement, Legitimate URL Shortener

### Add your comment and screenshots

1. When the ``AdGuard Annoyances`` filter is enabled, the site detects uBlock. 
Filter that fixes but displays information about cookies.

``@@||spolecznosci.mgr.consensu.org/v2/*$domain=shinden.pl``

<details><summary>Video:</summary>

https://user-images.githubusercontent.com/12976368/196039279-f2037b25-c553-4bee-83a3-d505a87d2eda.mp4

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by szyha** [comment] 2022-10-17 14:19
It is not necessary to have an account. The site blocks the list if the browser prefers another language besides Polish maybe also by non-Polish IP.


https://user-images.githubusercontent.com/12976368/196201356-343b9a32-84c4-4135-acea-1328d1f1a180.mp4

**Comment by Alex-302** [comment] 2022-10-19 07:27
I still don't see episodes

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/196624633-eb6cddf1-5521-4ae5-9f64-7b70ad9250d6.png)


</details>

@AdamWr Could you please take a look?

**Comment by AdamWr** [comment] 2022-10-19 08:05
I see episode lists here - `https://shinden.pl/episode/57705-chainsaw-man/view/216084` and I cannot reproduce it with AdGuard (as I recall, it's fixed by a rule which is not supported by uBlock Origin).
We also have similar exception for platforms which do not support JavaScript rules, so I will add uBlock to those rules.

**Closed** 2022-10-19 08:05 UTC
Labels: A: In progress, Unsorted, A: Waiting for data
