### ISSUE TITLE
The URL was blocked by a content blocker

### ISSUE THREAD

**Issue by einsteinbqat** [AdguardTeam/AdguardFilters#35485] opened 2019-06-19 00:42 UTC
### Steps to reproduce

Click link inside an email from Air Canada.

### Expected behavior
Open link in browser, load the page

### Actual behavior
Error message
Safari can’t open the page "https://t.mail.aircanada.com/r/?id=h1195abda,833f45b,8343fa9&p1=137622619&p2=62341002&p3=135283754&p4=62341002". The error is: "The URL was blocked by a content blocker" (WebKitErrorDomain:104)

### Your environment
* AdGuard AdBlocker extension version: 1.2.1
* Environment name and version: Safari Version 12.1.1 (13607.2.6.1.2)
* Filters you use in AdGuard: Base, Mobile, Spyware, Annoyances, Malware, NoCoin, French
* Any other browser extensions you have installed:

**Comment by Alex-302** [comment] 2019-06-19 09:02
@einsteinbqat moved your issue to correct repository.

**Comment by Alex-302** [comment] 2019-06-19 09:09
It seems this link is not working because aircanada.demdex.net cannot be resolved by DNS.

**Comment by einsteinbqat** [comment] 2019-06-19 11:13
The filter lists somehow does not appear in the original post. But it's there. Let me delete the screenshot part of the OP, maybe it'll show up.

**Comment by Alex-302** [comment] 2019-06-19 12:52
Could you please open developer tools -> console, reproduce an issue and make screenshot of console?
https://support.apple.com/guide/safari/sfri20948/mac

**Comment by einsteinbqat** [comment] 2019-06-20 00:34
The link opens just fine in Firefox, but fails in Safari.

**Comment by einsteinbqat** [comment] 2019-06-20 00:38
> Could you please open developer tools -> console, reproduce an issue and make screenshot of console?
> https://support.apple.com/guide/safari/sfri20948/mac

You mean the JS Console?

**Comment by einsteinbqat** [comment] 2019-06-21 02:24
![Screen Shot 2019-06-20 at 22 23 47](https://user-images.githubusercontent.com/48373997/59893188-22dad180-93aa-11e9-84a9-134c4a112c32.png)

**Comment by einsteinbqat** [comment] 2019-06-21 02:43
So here. For some reasons, if either or both of Adguard Mobile and Malware are enabled for Safari, the site will NOT load. Both must be off for the site to load.

Will work if enabled filters are: Adguard Base, Tracking, Annoyances, NoCoin, French

Will NOT work if enabled filters are:
Adguard Base, Mobile, Tracking, Annoyances, Malware, NoCoin, French
-OR-
Adguard Base, Mobile, Tracking, Annoyances, NoCoin, French
-OR-
Adguard Base, Tracking, Annoyances, Malware, NoCoin, French

**Comment by Alex-302** [comment] 2019-06-21 16:06
please check in custom filter
`@@||aircanada.demdex.net/event?d_event=click`

**Comment by einsteinbqat** [comment] 2019-06-22 03:26
> please check in custom filter
> `@@||aircanada.demdex.net/event?d_event=click`

Then this happens :
![Screen Shot 2019-06-21 at 23 25 58](https://user-images.githubusercontent.com/48373997/59958910-fb543980-947b-11e9-8389-a2c97f13c7ae.png)

**Comment by Alex-302** [comment] 2019-06-24 13:12
Please add `@@||ad.doubleclick.net/ddm/clk/` with previous `@@||aircanada.demdex.net/event?d_event=click`

**Comment by einsteinbqat** [comment] 2019-06-24 16:10
> Please add `@@||ad.doubleclick.net/ddm/clk/` with previous `@@||aircanada.demdex.net/event?d_event=click`

It doesn't work. Getting the same error as above.

**Comment by Alex-302** [comment] 2019-06-25 11:05
Strange. Do you have another ad blockers?

**Comment by einsteinbqat** [comment] 2019-06-25 21:11
No. Adguard is my only ad blocker.

**Comment by einsteinbqat** [comment] 2019-06-25 21:12
Disabling Malware and Mobile, makes it work.

**Comment by Alex-302** [comment] 2019-06-26 11:31
Please check without  Malware filter only.

**Comment by einsteinbqat** [comment] 2019-06-26 11:39
Like I said in a previous comment, if one of the two (Malware, Mobile) is active, it won't work. Both *must* be off.

**Comment by Alex-302** [comment] 2019-06-26 13:54
Please select this checkbox and reproduce with Mobile filter only
![image](https://user-images.githubusercontent.com/8361299/60185722-1388d780-9833-11e9-870d-77aac76d3354.png)

**Comment by einsteinbqat** [comment] 2019-06-30 14:20
Sorry for the delay! Will do in a few.

**Comment by einsteinbqat** [comment] 2019-06-30 14:51
![Screen Shot 2019-06-30 at 10 48 53](https://user-images.githubusercontent.com/48373997/60398359-f7cc4c80-9b24-11e9-9cf8-18ed3745bfcd.png)
![Screen Shot 2019-06-30 at 10 50 35](https://user-images.githubusercontent.com/48373997/60398362-fb5fd380-9b24-11e9-9bec-058657434eab.png)

**Comment by Alex-302** [comment] 2019-07-01 10:40
Strange. That exclusions must unblock this URL.
Could you please provide remove access?

**Comment by einsteinbqat** [comment] 2019-07-01 15:52
You mean remote access? I don't see how we will manage that since we will certainly have incompatible schedules, like I'd be at work or something.

Also, I mentioned in a previous post that the link works fine with Firefox. Well that changed, too. I get a blank page, stuck at this link : https://ad.doubleclick.net/ddm/clk/400677037;200731202;m?https://www.aircanada.com/ca/fr/aco/home/book/special-offers/skytrax.html?acid=em%7c62341002%7c137622619

I'm starting to wonder if this DoubleClick link has not somehow expired, and stopped working? Therefore, we won't solve this problem until I get another Air Canada email, perhaps.

I've tried with MS Edge Dev for macOS, and get an error, too. And it's just the browser, no extension or anything other than the browser itself.

I believe that what started with a filter problem has changed into something beyond simple filter rules.

**Comment by Alex-302** [comment] 2019-07-01 17:23
> until I get another Air Canada email

you can check with an old email.

Please check these wide exclusions:
```
@@||ad.doubleclick.net
@@t.mail.aircanada.com
```

Also, please record HAR file in Chrome or FF
https://toolbox.googleapps.com/apps/har_analyzer/
Open private tab, prepare to record HAR using description above and copy-paste the link from email. And attach it as zip archive.

**Comment by einsteinbqat** [comment] 2019-07-02 03:26
This is Microsoft Edge Dev for macOS, no Adguard, no extension or anything else.
![Screen Shot 2019-07-01 at 23 24 03](https://user-images.githubusercontent.com/48373997/60480425-7aedbf80-9c57-11e9-9c73-eb533913aede.png)
[chromewebdata.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/3348159/chromewebdata.har.zip)

**Comment by einsteinbqat** [comment] 2019-07-02 03:41
This is Firefox
![Screen Shot 2019-07-01 at 23 40 26](https://user-images.githubusercontent.com/48373997/60481017-bd180080-9c59-11e9-8452-48ab0426d8fa.png)

![Screen Shot 2019-07-01 at 23 33 55](https://user-images.githubusercontent.com/48373997/60480884-43801280-9c59-11e9-9873-62644b988b10.png)

![Screen Shot 2019-07-01 at 23 34 08](https://user-images.githubusercontent.com/48373997/60480889-47ac3000-9c59-11e9-9e06-e9533fb76a03.png)

![Screen Shot 2019-07-01 at 23 40 59](https://user-images.githubusercontent.com/48373997/60481034-c739ff00-9c59-11e9-8f2c-77c21eb5f4ad.png)

**Comment by einsteinbqat** [comment] 2019-07-02 03:53
This is Safari

The Network tab shows nothing. Therefore, cannot export any HAR file.

![Screen Shot 2019-07-01 at 23 49 03](https://user-images.githubusercontent.com/48373997/60481422-4419a880-9c5b-11e9-9224-af113d72b6fb.png)

![Screen Shot 2019-07-01 at 23 49 31](https://user-images.githubusercontent.com/48373997/60481424-47149900-9c5b-11e9-908a-65d2ee1d2b05.png)

**Comment by Alex-302** [comment] 2019-07-02 11:52
It seems doubleclick is blocked by another program/extension/DNS, or the link is obsolete.
Please try to open in Safari this URL `ad.doubleclick.net`

**Comment by einsteinbqat** [comment] 2019-07-02 23:33
It doesn't work at work on Firefox/Win10 or Edge/Win10. So I am starting to believe that the URL has a limited lifetime. So, I guess we will find out whenever the next Air Canada newletter comes in.

**Comment by Alex-302** [comment] 2019-07-08 10:22
Ok. In general, if you don't see `Blocked by content blocker` of something like than in console - domain is not blocked(at least by AdGuard:) ).

**Comment by einsteinbqat** [comment] 2019-07-12 03:28
> Ok. In general, if you don't see `Blocked by content blocker` of something like than in console - domain is not blocked(at least by AdGuard:) ).

New Air Canada e-mail!

New link : (https://t.mail.aircanada.com/r/?id=h13440a23,8aacccc,8aadb4a&p1=145411276&p2=62341002&p3=143451734&p4=62341002)

Stop at this link : (https://ad.doubleclick.net/ddm/clk/416236137;217559833;l?https://www.aircanada.com/ca/fr/aco/home/book/special-offers/auckland-partner.html?acid=em%7c62341002%7c145411276)

This is the error :
![Screen Shot 2019-07-11 at 23 26 27](https://user-images.githubusercontent.com/48373997/61100225-5651ce80-a433-11e9-8a49-833b2781fb14.png)

These are the filters :
![Screen Shot 2019-07-11 at 23 27 17](https://user-images.githubusercontent.com/48373997/61100257-800af580-a433-11e9-9a06-662d162565aa.png)

**Comment by einsteinbqat** [comment] 2019-07-14 05:01
@Alex-302 Like I said, the link opens without any problem in Firefox.

These are the Adguard settings in Firefox:
![Screen Shot 2019-07-14 at 00 54 57](https://user-images.githubusercontent.com/48373997/61179525-46bcbc00-a5d2-11e9-9db1-2e9377fc4cd3.png)

![Screen Shot 2019-07-14 at 00 55 20](https://user-images.githubusercontent.com/48373997/61179528-4ae8d980-a5d2-11e9-9939-1f4174e003da.png)

This is the Firefox Web Console:
![Screen Shot 2019-07-14 at 00 58 05](https://user-images.githubusercontent.com/48373997/61179558-a74bf900-a5d2-11e9-90ca-becdf03bce70.png)

This is the Firefox Network tab in a HAR file:
[www.aircanada.com_Archive [19-07-14 00-58-35].har.zip](https://github.com/AdguardTeam/AdguardFilters/files/3389475/www.aircanada.com_Archive.19-07-14.00-58-35.har.zip)

**Comment by einsteinbqat** [comment] 2019-07-14 05:05
MS Edge on Mac works, too, but that normal since there is no content blocking or adblocker installed.

MS Edge Console:
![Screen Shot 2019-07-14 at 01 04 39](https://user-images.githubusercontent.com/48373997/61179589-6f918100-a5d3-11e9-919d-4147c1d5a879.png)

MS Edge HAR file:
[www.aircanada.com.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/3389479/www.aircanada.com.har.zip)

**Comment by Alex-302** [comment] 2019-07-14 18:35
Damn Safari. New link works fine without additional exclusions in macOS, but not in iOS, even with exclusions.

**Comment by einsteinbqat** [comment] 2019-07-15 00:36
> Damn Safari. New link works fine without additional exclusions in macOS, but not in iOS, even with exclusions.

@Alex-302 It only works for me if Malware filters are deactivated.

**Comment by Alex-302** [comment] 2019-07-15 08:45
I don't see the rules in this filter, which can block these domains

**Comment by einsteinbqat** [comment] 2019-07-15 14:11
@Alex-302 I don't understand myself

**Comment by Alex-302** [comment] 2019-07-15 21:32
Better disable it then

**Closed** 2019-09-18 13:36 UTC
Labels: A: Cannot reproduce
