### ISSUE TITLE
bypass time / skip time count of shortlink

### ISSUE THREAD

**Issue by FinderID** [AdguardTeam/AdguardFilters#139810] opened 2023-01-11 17:01 UTC
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

direct link : https://blogmado.com/wisuRq7

### Proposed solution

skip / bypass the time count

### Additional information

![image](https://user-images.githubusercontent.com/57831066/211869299-b753cf3e-f017-4c19-bc0d-fd7a1b03d8d2.png)

**Comment by AdamWr** [comment] 2023-01-12 09:51
Looks like duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/139845

**Closed by AdamWr** 2023-01-12 09:51 UTC
Labels: A: In progress

**Comment by FinderID** [comment] 2023-01-12 15:24
yes, im sorry have duplicate it.
