### ISSUE TITLE
zoutons.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93862] opened 2021-09-05 23:50 UTC
**Issue URL (Annoyance)**:
https://zoutons.com/news/udemy-free-coupons

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132144715-2a496183-41f2-43ee-8e34-31739e24d7c5.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-09-21 08:21
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/93248

**Closed by AdamWr** 2021-09-21 08:21 UTC
