### ISSUE TITLE
Websites using I10C scripts

### ISSUE THREAD

**Issue by theseanl** [AdguardTeam/AdguardFilters#3844] opened 2016-12-22 13:47 UTC
We can validate each sites reportedly having instartlogic scripts in the following way:
enable 
```
#%#var a = {}; Object.defineProperty( window, 'INSTART_TARGET_NAME', { get: function(){ return a; }, set: function(i){ alert(i); a = i; } });
```

Once their 'nanovisor' script at the start of the html document is executed, it sets the value of INSTART_TARGET_NAME which seems to be to avoid executing it twice.

For sites of which the value is `abd`, I guess we can remove the script, so we can use 
```$$script[tag-content="===typeof I10C"][min-length="20000"][max-length="32768"]``` or 
```
#%#(function(){var d=Math.random().toString(36).substring(2),e=function(){},f=function(){return!1};window.I10C=new Proxy({},{get:function(b,a){switch(a){case "CanRun":return f;case "Morph":return void 0;default:if(void 0===b[a])throw Error(d);return b[a]}},set:function(b,a,c){switch(a){case "CanRun":break;default:b[a]=c}}});window.INSTART=new Proxy({},{get:function(b,a){switch(a){case "Init":return e;default:if(void 0===b[a])throw Error(d);return b[a]}},set:function(b,a,c){switch(a){case "Init":break;default:b[a]= c}}})})();
```

(based on a scriptlet being used in uBO-extra https://github.com/uBlockOrigin/uAssets/issues/227)

For sites of which the value is `abd.html_streaming`, those use `I10C.HtmlStreaming.InsertTag()` and other apis to write htmls (mostly script tags) to the document which are necessary to their functioning. 

There was one website which had a value different from above, `opshead.com` had `optimus.html_streaming` and it didn't do any obnoxious stuff, they seems to be using it for other purposes than fighting with adblockers.

Attached a result - [InstartLogic.zip](https://github.com/AdguardTeam/AdguardFilters/files/1111083/InstartLogic.zip)
(Updated 29 June)

Sites marked with 'x' were those didn't set INSTART_TARGET_NAME. Maybe they are testing it in their own environment, or using it for certain targeted population.

**Comment by ameshkov** [comment] 2016-12-22 13:54
@Alex-302 we may need your help as well.

**Comment by ameshkov** [comment] 2016-12-22 13:59
For desktop & android:

Let's use `$$script[tag-content="===typeof I10C"][min-length="20000"][max-length="32768"]` for `abd` websites right away. But only for those who really use g00 stuff to reinject the ads.

**Comment by Alex-302** [comment] 2016-12-22 14:43
@ameshkov 

> we may need your help as well.

how can I help?

**Comment by ghajini** [comment] 2017-03-25 16:02
@seanl-adg ,your fix doesn't work...tried google chrome 59 canary....adguard...default filter updated......

![screenshot 201](https://cloud.githubusercontent.com/assets/20338483/24323839/e456b708-11a1-11e7-93c1-b803734648a0.png)
![screenshot 202](https://cloud.githubusercontent.com/assets/20338483/24323840/e45fd810-11a1-11e7-8ef3-d855276dd335.png)
![screenshot 203](https://cloud.githubusercontent.com/assets/20338483/24323841/e4634cf2-11a1-11e7-8267-4b013f1ee593.png)

**Comment by ghajini** [comment] 2017-03-26 09:47
test site `www.sandiegotribune.com`
Need to update anti IL code again
google chrome 59
adguard 2.5.11
do i need to use adguard for windows standalone software

**Comment by seanl-adg** [comment] 2017-04-04 04:12
@ghajini Hi, you will have to use adguard 2.6.0 version or above to apply our current anti IL code. 
2.6 version is not yet released in chrome webstore. Please wait until its release, or try building the adguard extension from the source code, which you can obtain at https://github.com/AdguardTeam/AdguardBrowserExtension/.
In 2.6 version, our JS rule is applied eariler than IL's code.

**Comment by F4z** [comment] 2017-04-17 22:38
I think, that they change their script again.
I see ads here -` http://www.chicagotribune.com/`

Adguard for Windows 6.1.331.1732

<details><summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/25107067/68548af2-23cd-11e7-8e4a-a2774ea524ec.png)

</details>

**Comment by ameshkov** [comment] 2017-04-17 22:45
Yep, not long ago:
`//copyright Fri Apr 14 2017 01:04:41 GMT+0000 (UTC)`

**Comment by ameshkov** [comment] 2017-04-17 22:53
Temporary solution for desktop programs and for Android:
`||chicagotribune.com^$replace=/<script>[\s\S]+?nanovisor injection[\s\S]+?<\/script>/<!-- Bye-bye g00 stuff -->/,important`

**Comment by ghajini** [comment] 2017-07-15 14:29
@seanl-adg 
something changed recently...i see this
![chrome_2017-07-15_19-55-48](https://user-images.githubusercontent.com/20338483/28240075-0e700fbe-6998-11e7-8246-3543834d7352.png)

**Comment by ghajini** [comment] 2017-07-19 18:40
@ameshkov and @seanl-adg

**Comment by seanl-adg** [comment] 2017-07-20 03:33
It was reproduced before, but currently I am not being served with a page with InstartLogic's stuff.

It seems that the browser extension is still cannot apply JS rules sufficiently fast. IL rules are applied on both `nationalpost.com` and `wrestlezone.com`.
@ameshkov Could you please confirm that it is because of timing issues?

**Comment by ghajini** [comment] 2017-07-22 15:43
there are issues with speed(if any)
***steps to reproduce***
first clear any cookies/data
navigate to url directly without previously entering homepage  e.g 
`http://www.sandiegouniontribune.com/entertainment/things-to-do/sd-me-woman-con-20170721-story.html`   
>you will not get IL/g00 spam/advertisements.....
***screenshot***
`http://prntscr.com/fyx67r`

now clear all cookies/data....
1. go to `www.sandiegotriune.com`

2.click any story, you will get destination page with full of ads and enormous cookies of g00...page then constantly reloads

screenshot
`https://prnt.sc/fyx5ab`


***ublock origin ,ubo extra combination loads page within seconds***

**Comment by ameshkov** [comment] 2017-07-22 23:38
> @ameshkov Could you please confirm that it is because of timing issues?

Looks like it is. And to have it sorted out we should execute that code from a content script.

Is that IL stuff bad enough to have a special case for them in the content script?

**Comment by ghajini** [comment] 2017-07-24 16:41
still got g00....going to homepage of `www.sandiegotribune.com` and clicking on any story invokes g00
http://prntscr.com/fzoxmx

ads
http://prntscr.com/fzoy0e

**Comment by ameshkov** [comment] 2017-07-30 20:29
> solution for g00 crap is possible only in standalone programs

Not really, what he means is that blocking IL stuff requires us to hard-code the anti-IL code into the extension instead of using the filtering rules.

**Comment by ghajini** [comment] 2017-08-19 14:11
Okk waiting for anti-IL code in next release of browser extension

**Comment by danidoedel** [comment] 2017-08-22 09:22
@seanl-adg Could you please look into the InstartLogic script again? It was updated last friday and the filter doesn't seem to work anymore.

**Comment by danidoedel** [comment] 2017-09-09 21:39
Some more sites using InstartLogic:

- http://www.afterellen.com/
- http://cattime.com/
- http://www.chroniclelive.co.uk/
- http://www.comingsoon.net/
- http://www.craveonline.com/
- http://www.dayzdb.com/
- http://dogtime.com/
- http://www.dotaoutpost.com/
- http://www.esohead.com/
- http://everquest.allakhazam.com/
- http://www.momtastic.com/
- http://musicfeeds.com.au/
- http://www.mustangandfords.com/
- http://www.realitytea.com/
- http://www.seattlepi.com/
- http://www.superherohype.com/
- http://www.thefashionspot.com/
- http://www.totalbeauty.com/
- http://www.trustedreviews.com/
- http://www.tv.com/
- http://www.tvguide.com/
- https://www.washingtonpost.com/

**Comment by danidoedel** [comment] 2017-09-23 13:34
Nice, no response at all... Anyone? @seanl-adg @ameshkov @Alex-302 @AdamWr

**Comment by ameshkov** [comment] 2017-09-25 13:16
@danidoedel sorry for the delay.

@AdamWr please check the websites list,  `$$` anti-IL rule should be updated.

**Comment by AdamWr** [comment] 2017-09-25 15:28
Added.

I wasn't able to reproduce IL script on these websites:
`http://www.chroniclelive.co.uk/`
`http://www.trustedreviews.com/`
`http://www.tv.com/`

**Comment by ghajini** [comment] 2017-09-25 16:53
@ameshkov 
Many users use adguard browser extension, adguard suffers instart logic crap(all mentioned sites) for browser extension users?
anybody working for browser extension users?

**Comment by BooBerry** [comment] 2017-09-25 16:57
Well, the problem is the browser extensions need to have the anti-IS hard coded within the extension to get it to work as they don't support the required $$script rules.

But, hopefully, things change...

**Comment by ghajini** [comment] 2017-09-25 17:13
@ameshkov , So its feature request - `$$ script rules` probably fits into milestone 3.0

**Comment by BooBerry** [comment] 2017-09-25 18:57
Yes, Adguard for Windows works. But if you read the above, @AdamWr couldn't reproduce IL on that website (tv.com). But, if you want, try adding this rule to the user filter in AdGuard for Windows;

`tv.com$$script[tag-content="==typeof t.IXC"][min-length="20000"][max-length="100000"]`

Also if you have the IL g00 cookies in your browser cache, you *should* remove them before retesting this. In fact, I'd recommend clearing the entire browser cache first.

**Comment by AdamWr** [comment] 2017-09-25 19:23
If I'm not wrong, this rule will not work in AdGuard 6.1, because there is limit/range for `$$` rules - https://github.com/AdguardTeam/AdguardForWindows/issues/1464
You need to install AdGuard Beta - https://github.com/AdguardTeam/AdguardForWindows/releases

By the way, I'm able to reproduce IL on `tv.com` with US IP.
I will check other two websites and I will add appropriate rules.

**Comment by ghajini** [comment] 2017-10-02 15:15
So if there limit for $$ rule ,instart logic can't wait for you,they always update weekly......
Then as per @AdamWr, user has only 1 choice I.e to stick to ***ublock origin+ubo extra***😒

**Comment by AdamWr** [comment] 2017-10-02 15:17
Limit is in AdGuard 6.1, it was fixed in AdGuard 6.2 Beta.

**Comment by danidoedel** [comment] 2017-10-08 10:44
@AdamWr Another site:

https://www.livescience.com/

**Comment by AdamWr** [comment] 2017-10-08 15:02
Added.

**Comment by danidoedel** [comment] 2017-10-12 17:24
@AdamWr And one more:

https://www.space.com/

**Comment by AdamWr** [comment] 2017-10-12 18:30
Added.

**Comment by danidoedel** [comment] 2017-11-11 20:23
@AdamWr A few more:

- http://www.slate.com/
- http://www.sportingnews.com/
- http://www.tomshardware.com/
- http://www.tomshardware.co.uk/
- https://www.tomshardware.de/
- http://www.tomshardware.fr/

**Comment by AdamWr** [comment] 2017-11-13 12:38
Added.
Thank you.

**Comment by danidoedel** [comment] 2017-11-18 14:43
@AdamWr Not working anymore on all these sites: https://github.com/AdguardTeam/AdguardFilters/blob/e4b850ebca8df17f7b161bd78a9520f617310d4a/EnglishFilter/sections/antiadblock.txt#L116

New site missing:

- https://www.laptopmag.com/

**Comment by BooBerry** [comment] 2017-11-20 11:16
I think https://www.msn.com/ is using IL now - I just found g00 MSN cookies in my browser cache.

**Comment by AdamWr** [comment] 2017-11-20 12:15
Fixed - `msn.com, livescience.com, newsarama.com, space.com, tomsguide.com, tomshardware.com, tomshardware.co.uk, tomshardware.de, tomshardware.fr`
Added - `laptopmag.com`

**Comment by danidoedel** [comment] 2017-12-28 19:16
@AdamWr Missing site:

http://opshead.com/

**Comment by AdamWr** [comment] 2017-12-28 21:50
Thank you, added.

**Comment by danidoedel** [comment] 2018-01-17 18:51
@AdamWr New sites:

- https://www.tomsguide.fr/
- https://www.salon.com/

**Comment by AdamWr** [comment] 2018-01-17 20:38
Added.
Thank you.

**Comment by AdamWr** [comment] 2018-01-22 23:57
Added.
Thank you.

**Comment by ghajini** [comment] 2018-01-23 12:54
@okiehsch, new sites, see above

**Comment by danidoedel** [comment] 2018-02-14 17:43
@AdamWr New site:

- http://www.tvguide.com/

**Comment by AdamWr** [comment] 2018-02-14 19:13
Added.
Thank you.

**Comment by danidoedel** [comment] 2018-03-05 19:22
@AdamWr New sites:

- https://www.emedicinehealth.com/
- https://www.medicinenet.com/

**Comment by AdamWr** [comment] 2018-03-06 09:39
Added.

**Comment by danidoedel** [comment] 2018-06-17 10:22
@AdamWr New site:

- http://tvtropes.org/

**Comment by AdamWr** [comment] 2018-06-18 10:20
Added.
Thank you.

**Closed** 2018-07-09 07:56 UTC
Labels: A: Closed, T: Anti Adblock Script
