### ISSUE TITLE
[Annoyance] Add salon.com rule to remove anti-adblock warning

### ISSUE THREAD

**Issue by GauthierPLM** [AdguardTeam/AdguardFilters#51691] opened 2020-03-17 13:30 UTC
Add the following rule to avoid modal that warn about adblocker:

`salon.com###adblockModal`

There is a scroll lock I couldn't fix.

Example page: https://www.salon.com/2020/03/17/european-college-warns-students-to-return-from-poorly-developed-us-during-pandemic/

Before:

![image](https://user-images.githubusercontent.com/2579741/76860705-bec33c00-685b-11ea-9413-41ff7b98b96c.png)

After:

![image](https://user-images.githubusercontent.com/2579741/76860654-ad7a2f80-685b-11ea-8c54-ba048740522d.png)

I would like to edit the filter myself, but it's too messy/complicated to read to do it by myself... Do you have a tool to easily manage it, that can order rules or offer a per-section view for it? Right now editing rules in your filters isn't an easy task...

**Comment by AdamWr** [comment] 2020-03-17 13:54
Do you have `AdGuard Annoyances filter` enabled?
If not, please enable it, update filters and then refresh website using `Ctrl + F5`.

**Comment by GauthierPLM** [comment] 2020-03-17 14:52
The `AdGuard Annoyances filter` is enabled, that's why I reported this issue.

I use AdGuard for Windows 7.4 nightly 9 and updated all filters before testing it again.

**Comment by AdamWr** [comment] 2020-03-17 15:09
Strange, I can't reproduce it with `AdGuard Annoyances filter` enabled.
Please add this rule to user filter and check the result:
`salon.com#%#//scriptlet("set-constant", "salon_config.show_shield_message", "0")`

**Comment by uBlock-user** [comment] 2020-03-17 15:10
@GauthierPLM setting `adFreeCheck`'s value to `null`, will also avoid the scroll issue and fix the anti-adblock together fyi.

**Comment by AdamWr** [comment] 2020-03-17 15:28
>setting `adFreeCheck`'s value to null, will also avoid the scroll issue and fix the anti-adblock together fyi.

Doesn't it break a website?
If I set `adFreeCheck` to `null` it causes that comments don't load.

**Comment by uBlock-user** [comment] 2020-03-17 15:31
> it causes that comments don't load.

Haven't tested comments for breakage. Are you sure it happens due to this ?

**Comment by AdamWr** [comment] 2020-03-17 15:38
Yes, it seems that it's caused by this rule.
I checked it with uBO and with this rule:
`salon.com##+js(set, adFreeCheck, null)`
and comments are broken.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/76872915-5da46400-686d-11ea-8e4b-d20371c82fb4.png)

</details>

If I remove this rule, then comments load correctly.

As I see, you removed this rule from uBO filters, so I think that it's fine.

**Comment by uBlock-user** [comment] 2020-03-17 15:50
I removed it because it's already fixed in uBO previously, but thanks for the feedback nonetheless.

**Comment by GauthierPLM** [comment] 2020-03-17 16:37
> Strange, I can't reproduce it with `AdGuard Annoyances filter` enabled.
> Please add this rule to user filter and check the result:
> `salon.com#%#//scriptlet("set-constant", "salon_config.show_shield_message", "0")`

This does not block the anti-adblock modal.

**Comment by AdamWr** [comment] 2020-03-17 17:00
> > Strange, I can't reproduce it with `AdGuard Annoyances filter` enabled.
> > Please add this rule to user filter and check the result:
> > `salon.com#%#//scriptlet("set-constant", "salon_config.show_shield_message", "0")`
> 
> This does not block the anti-adblock modal.

With this rule anti-adblock modal doesn't appear on my end (even if I disable `AdGuard Annoyances filter`).

@AdguardTeam/filters-maintainers Could you please check it?

**Comment by AdamWr** [comment] 2020-03-17 17:06
By the way, do you have any rule for this website in user`s rules?

**Comment by GauthierPLM** [comment] 2020-03-17 17:10
I have the rule that I wrote in my first message, but I disabled it to test your rule.

**Comment by BlazDT** [comment] 2020-03-17 17:15
Not reproduced.

**Comment by GauthierPLM** [comment] 2020-03-17 18:06
[20200317_adguard_filtering_log_records.zip](https://github.com/AdguardTeam/AdguardFilters/files/4345017/20200317_adguard_filtering_log_records.zip)

There are my filtering logs. If i can provide more infos, let me know.

**Comment by AdamWr** [comment] 2020-03-17 20:12
Unfortunately there is nothing interesting in this log.
Please check these rules one by one (firstly please disable/remove previous rule, add the new one, wait until it will be applied and then refresh website two times):
`salon.com#%#//scriptlet("set-constant", "data.ad_free", "true")`
or
`salon.com#%#AG_setConstant('data.ad_free', 'true');`
or
`salon.com#%#AG_setConstant('salon_config.show_shield_message', '0');`

**Comment by GauthierPLM** [comment] 2020-03-17 20:18
These three rules works when applied individually.

**Comment by AdamWr** [comment] 2020-03-17 20:25
Ok, added the first rule to Annoyances filter, update should be available in 1-2 hours.
Thank you for your answer.

**Closed by AdamWr** 2020-03-17 20:25 UTC
Labels: A: Resolved
