### ISSUE TITLE
http://www.slrclub.com Incorrect blocking - Mac OS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5741] opened 2017-07-18 13:46 UTC
***Description***:
* **Current behaviour**: 

Adguard stops the file from being downloaded (from:
 http://www.slrclub.com/bbs/vx2.php?id=slr_review&no=570 )
when disabling Aguard (even having extension enabled) it works fine

<details><summary>Screenshot:</summary>

<img width="1189" alt="2017-07-18 5 45 38" src="https://user-images.githubusercontent.com/28784344/28320006-1da12328-6bd8-11e7-8a90-ef086978c11e.png">

</details>

***Steps to reproduce the problem***:
- Go to the website, find any image, press "JPG Download"
- turn off Adguard and try to reproduce the issue 
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0 , 2, 3, 4, 10 , 227 

Ticket ID (if exists): | 1593847

**Comment by Alex-302** [comment] 2017-07-19 11:18
It works on my side.


> Adguard stops the file

What does it mean? Is it caused by filters?

**Comment by Alex-302** [comment] 2017-07-19 11:19
@AdamWr @seanl-adg please check on your side.

**Comment by AdamWr** [comment] 2017-07-19 11:48
I can not reproduce. It works on my end.

**Comment by ypetruk** [comment] 2017-07-20 00:23
it loads the picture only when Adguard is disabled

**Comment by Alex-302** [comment] 2017-07-20 12:45
@ypetruk which filter causes it?

**Comment by seanl-adg** [comment] 2017-07-20 21:18
Not reproduced on my end with AG for Windows.

**Comment by ypetruk** [comment] 2017-07-24 04:56
it`s not a filter problem on my side
it loads only when Adguard standalone app is disabled

**Comment by Alex-302** [comment] 2017-07-24 10:55
@ypetruk which Adguard version?
@altokarev could you please check it on your end?

**Comment by ypetruk** [comment] 2017-07-24 11:25
Mac (1.4.1)

**Comment by Alex-302** [comment] 2017-08-17 08:46
Which filter breaks it?

**Comment by Alex-302** [comment] 2017-08-17 08:46
It it still actual?

**Comment by altokarev** [comment] 2017-08-17 10:17
Reproduced on my side. Adguard app blocks jpeg loading from FTP link.

Disabling an Adguard solves the problem. 

Filtering log shows nothing related.

**Comment by Alex-302** [comment] 2017-08-17 11:02
Check with exclusions.

**Comment by altokarev** [comment] 2017-08-17 11:06
Which exclusions?

**Comment by Alex-302** [comment] 2017-08-17 11:07
$elemhide / $jsinject / $document

**Comment by altokarev** [comment] 2017-08-17 11:20
Didn't help. I doubt this could be a solution.

The key problem is that ftp://rawdata.slrclub.com/body/sony/1706_a9/ doesn't load at all. There is something wrong with `ftp://` link.

Here is a record: https://performix.slack.com/files/atokarev/F6PUA5AJY/slr.mov

**Comment by Alex-302** [comment] 2017-08-17 16:17
So it can't be fixed by filters.

**Closed** 2017-08-22 18:12 UTC
Labels: Cannot Reproduce
