### ISSUE TITLE
https://extramovies.bar/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91391] opened 2021-08-17 17:06 UTC
**Issue URL (Annoyance)**:

https://extramovies.bar/
<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129769995-e0fde30a-61c7-4a7d-996e-1145ac8b2020.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-08-17 17:19
Looks like duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/91048

**Closed by AdamWr** 2021-08-17 17:19 UTC
