### ISSUE TITLE
Website blocked due to presence of AdGuard

### ISSUE THREAD

**Issue by vivshah56** [AdguardTeam/AdguardFilters#23968] opened 2018-10-16 07:42 UTC
***Description***:
The following website fails to load due to presence of AdGuard 

https://einthusan.tv/

The page immediately loads the anti adblock script

* **Current behaviour**: 
Adblock script blocks the site contents

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 
Website should load

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

Open the website : https://einthusan.tv/ 

***System configuration***
Google Chrome on macOS

**Filters:**

Most updated filters - last updated on Oct 15 2018

**Comment by AdamWr** [comment] 2018-10-16 08:53
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/23960

**Closed by AdamWr** 2018-10-16 08:53 UTC
