### ISSUE TITLE
theplanetd.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#91149] opened 2021-08-15 16:34 UTC
**Issue URL (Annoyance)**: https://theplanetd.com/youtube-travel-vloggers/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/129485591-2c478afb-b906-4235-9d21-737c0fd0f73f.png)
</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-08-18 13:35
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/90646

**Closed by AdamWr** 2021-08-18 13:35 UTC
