### ISSUE TITLE
theteche.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98189] opened 2021-10-26 12:59 UTC
**Issue URL (Ads/Annoyance)**:
https://theteche.com/what-is-diaphragm-in-pressure-sensor/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/138883646-35bf1983-02d9-48b6-aa8e-8efd118ed103.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-11-08 11:07
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/98187

**Closed by AdamWr** 2021-11-08 11:07 UTC
