### ISSUE TITLE
rchat app - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4361] opened 2017-02-12 11:42 UTC
https://play.google.com/store/apps/details?id=net.devking.randomchat.android

Could not reproduce, asked for logs. 

Screenshots:
<details>

![screenshot_20170211-061622](https://cloud.githubusercontent.com/assets/15856304/22861712/c4a28368-f128-11e6-8ee6-f5a5206f4a17.png)
![screenshot_20170211-054202](https://cloud.githubusercontent.com/assets/15856304/22861713/c62be33c-f128-11e6-9c83-1a15cffdb6ef.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard filters: |  2, 3, 4, 7, 11 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1502461 woth LOGS

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment] 2017-02-13 12:53
I can't help.
Filed an issue
https://github.com/AdguardTeam/AdguardForAndroid/issues/1050

**Comment by Alex-302** [comment] 2017-02-15 12:17
we should wait for the next Adguard build. This app uses non-standard ports.

**Comment by hal109** [comment] 2017-02-17 06:07
I have sucseeded the ads of this app. I added 280 blocker [https://70i.net/files/70i_net_adblock.txt] and checked filter DNS request, the ads removed!

**Comment by Alex-302** [comment] 2017-02-17 11:00
@hal109 please temporary disable this filter and check with DNS filtering.
If the ads will be shown, disable all filters and add `280 blocker` 
```
1. Open Adguard and go to "Settings".
2. Choose "Advanced" in the left menu.
3. Set "Logging level" to "Record HTTP requests". It's desirable to close all background apps that don't concern the problem beforehand.
4. Reproduce the problem and remember the time when you start this app. 

You can also download logs directly:
/storage/emulated/Android/data/com.adguard.android/cache/log
or, depending on device,
/sdcard/Android/com.adguard.android/cache/log or
/sdcard/data/Android/com.adguard.android/cache/log or
/sdcard/Android/data/com.adguard.android/
```

**Comment by hal109** [comment] 2017-02-17 12:12
I was not sure what I should do, and then I have cleared the User Filter
and added 280 blocker again, ads are shown!



2017/02/17 20:00 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-02-17 12:35
Maybe they are was not blocked before. Is DNS filtering enabled?
We will able to block these ads in the next build without DNS filtering.

**Comment by hal109** [comment] 2017-02-17 13:03
I'm not sure what I did, but I made filters enabled and checked with DNS
filtering again, ads removed!

2017/02/17 20:00 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-02-17 21:15
Strange. Could you, please, collect the log of HTTP requests?

**Comment by hal109** [comment] 2017-02-17 23:15
Sorry, I don't know how to stop background apps.

**Comment by hal109** [comment] 2017-02-18 01:45
I had uninstalled and installed Adguard again. And then set "Logging level"
to "Record HTTP request". I added 208 blocker and checked with DNS
filtering, the rchat ads removed.

2017/02/18 6:16 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-02-20 14:21
could you send me new log with time, when you launch the app? Or, you can send message to our support and add "For Alex"

**Comment by hal109** [comment] 2017-02-20 14:43
For Alex.
Sorry, I don't remember the exact time when I launched the app. Maybe it's
in the morning in 20170218.

2017/02/20 23:21 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-02-20 15:47
You can close this app and collect fresh log:) Ok?

**Comment by hal109** [comment] 2017-02-20 20:41
Is this app Adguard? I closed Adguard and collect fresh logs now.

2017/02/21 0:47 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-02-20 21:04
No:)
1. Close rchat(not just swipe it)
2. Remember current time:)
3. Start the app and reproduce the ads
4. Send me log and time. The log is placed in
/storage/emulated/Android/data/com.adguard.android/cache/log
or, depending on device,
/sdcard/Android/com.adguard.android/cache/log or
/sdcard/data/Android/com.adguard.android/cache/log or
/sdcard/Android/data/com.adguard.android/
***or*** send message+log to out support with the time and GitHub link https://github.com/AdguardTeam/AdguardFilters/issues/4361

**Comment by hal109** [comment] 2017-02-20 22:27
Sorry. I don't know how to open

/storage/emulated/Android/data/com.adguard.android/cache/log

Am I able to do it only in my Galaxy S7 Edge?

2017/02/21 6:04 "Alex" <notifications@github.com>:

**Comment by hal109** [comment] 2017-02-21 00:13
The time is 9:09

2017/02/21 6:04 "Alex" <notifications@github.com>:

**Comment by hal109** [comment] 2017-02-21 09:49
I could not find the log because my file manager uses different path.

MainStorage/Android/com.adguard.android/cache/log

2017/02/21 6:04 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-02-21 10:00
@hal109 you can just send feedback, then post Ticket ID here
<details>

![image](http://imagizer.imageshack.com/img924/4597/53Zdoa.png)
</details>
I will find your log in the support.

**Comment by Alex-302** [comment] 2017-02-21 10:07
the log on S7 is located in
`internalstorage/Android/data/com.adguard.android/cache/log`

**Comment by zebrum** [comment] 2017-02-22 09:06
@Alex-302 
ID: 1502461

[debug (1).txt.zip](https://github.com/AdguardTeam/AdguardFilters/files/792771/debug.1.txt.zip)

**Comment by Alex-302** [comment] 2017-02-22 12:50
as I see, these requests are blocked
```
http://adn.admixer.co.kr/log?app_key=hant4ssm&model=SC-02H&sdk_version=1.3.16&os_version=6.0.1&os=android&network=3G&log_type=imp&ads_type=banner&slot_req=1&adnet_fail=admob&adnet_succ=cauly&udid=1d4bdad2-6c35-4afb-aab1-238548d75213&lang=ja
http://config.inmobi.com/config-server/v1/config/secure.cfg
https://sdkm.w.inmobi.com/
http://miximg.nasmedia.co.kr/library/admixer_0.618.apk
```
@hal109 when the app was launched?

**Comment by hal109** [comment] 2017-02-22 22:18
the time was 9:09, or 8:55.



2017/02/22 21:50 "Alex" <notifications@github.com>:

**Comment by hal109** [comment] 2017-02-23 07:55
I've sent new feedback with system info. Please see it.

2017/02/17 20:00 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-02-23 14:09
@hal109 did you see ads? All advertising requests are blocked by mobile filter.

**Comment by hal109** [comment] 2017-02-23 14:15
yup. ads are shown. I used the app without checking DNS Filtering today.

2017/02/23 23:09 "Alex" <notifications@github.com>:

@hal109 <https://github.com/hal109> did you see ads? All advertising
requests are blocked by mobile filter.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardFilters/issues/4361#issuecomment-282000495>,
or mute the thread

**Comment by Alex-302** [comment] 2017-02-23 14:21
Please make the same with DNS filtering(and remember the time:) ), but disable all filters, except mobile and `280 blocker`. I will try to find the rules, which should be added to mobile filter.

**Comment by hal109** [comment] 2017-02-23 14:50
I've sent a feedback twice. The second one is right.

2017/02/23 23:21 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-02-27 10:23
Ok. We should to wait for new build.

**Comment by hal109** [comment] 2017-02-27 11:10
Thanks for your help.

2017/02/27 19:23 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-02-27 11:11
Thank you)

**Comment by Alex-302** [comment] 2017-03-02 14:29
Found few ad requests. Added to mobile filter.
You can add(not replace) these ports to `filtered ports` in low-level settings and restart protection
`8200,10606,11000`

**Comment by hal109** [comment] 2017-03-02 14:37
Sorry. How can I do it?

2017/03/02 23:29 "Alex" <notifications@github.com>:

Found few ad requests. Added to mobile filter.
You can add(not replace) these ports to filtered ports in low-level
settings and restart protection
8200,10606,11000

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardFilters/issues/4361#issuecomment-283667908>,
or mute the thread

**Comment by Alex-302** [comment] 2017-03-02 14:49
Go to `Settings -> Advanced -> Low level settings` and find `pref.filtered.ports`
Tap on it and add that ports.
The result will be string:
`80,443,8200,10606,11000`

**Comment by hal109** [comment] 2017-03-02 14:54
What about the port 3148?

2017/03/02 23:49 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-03-02 14:54
3128?

**Comment by Alex-302** [comment] 2017-03-02 14:55
Just add 8200,10606,11000 to the end of existing string

**Comment by hal109** [comment] 2017-03-02 14:56
Yes. Maybe 3128.

2017/03/02 23:54 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-03-02 15:24
New rules are not in mobile filter yet. Please wait one hour.

**Comment by hal109** [comment] 2017-03-02 15:27
okay.

2017/03/03 0:24 "Alex" <notifications@github.com>:

**Comment by hal109** [comment] 2017-03-02 20:12
Without DNS Filtering ads are shown!

2017/03/03 0:26 "Hal Oyama" <noir.mont.blanc@gmail.com>:

**Comment by Alex-302** [comment] 2017-03-02 20:34
Hmmm...
Could you install new beta version? On my side it blocks these ads.
Port settings will not be updated, so you may to copy-paste this string:
`80,443,1024:65535`

**Comment by hal109** [comment] 2017-03-02 20:49
Sorry, Pls tell me how to install new beta virsion.

2017/03/03 5:34 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-03-02 21:16
Download link:
https://github.com/AdguardTeam/AdguardForAndroid/releases/download/v2.9.1-beta/adguard_2.9.1_beta.apk
After install go to `Settings -> Advanced -> Low level settings` and find `pref.filtered.ports`
Tap on it and add that ports.
The result will be string:
`80,443,1024:65535`
and restart protection.

Release notes:
https://github.com/AdguardTeam/AdguardForAndroid/releases

**Comment by hal109** [comment] 2017-03-02 21:53
Do you mean replace the filtered ports?
How about 80,443,3128,8200,10606,11000?


2017/03/03 6:16 "Alex" <notifications@github.com>:

**Comment by hal109** [comment] 2017-03-02 22:22
I installed the new beta virsion and tryed several ways.

80,443,3128,8200,10606,11000
with DNS Filtering: ads removed.
wlthout: ads are shown.

80,443,1024,65535
with: ads are shown.
without: ads are shown.

And then what should I do next?

2017/03/03 6:53 "Hal Oyama" <noir.mont.blanc@gmail.com>:

**Comment by Alex-302** [comment] 2017-03-02 22:24
No, use `80,443,1024:65535`
1024:65535 - is a range of ports from 1024 to 65535
don't replace `:` by comma

**Comment by hal109** [comment] 2017-03-02 22:32
Great! Ads removed!

2017/03/03 7:24 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment] 2017-03-02 22:34
Excellent! :)

**Comment by hal109** [comment] 2017-03-02 22:37
Thanks a lot!

2017/03/03 7:34 "Alex" <notifications@github.com>:

**Closed** 2017-03-03 09:31 UTC
Labels: Ads, Android
