### ISSUE TITLE
Adblock detected 

### ISSUE THREAD

**Issue by kumar041** [AdguardTeam/AdguardFilters#156342] opened 2023-07-10 16:49 UTC
Hi devs,

I am using your adguard for Android, I am trying to download from this website called devuploads file hosting site which redirects to another site, when land on this page https://thecubexguide.com/kestrel-web-server-vs-nginx-which-is-better-for-your-web-application/

It says adblock detected so website is not allowing to download from it.

Could you kindly tell me how to slove it.

Error screen shot

![Screenshot_20230710-222232_Chrome.png](https://github.com/AdguardTeam/AdguardForAndroid/assets/97349871/d422a58b-f157-42b3-91a2-a9d402362b50)

Adguard version

![Screenshot_20230710-221825_AdGuard.png](https://github.com/AdguardTeam/AdguardForAndroid/assets/97349871/454f8335-9594-469d-863a-9e2cbc5f25e7)

My Android version

![Screenshot_20230710-221840_Settings.png](https://github.com/AdguardTeam/AdguardForAndroid/assets/97349871/6c2e4486-f16b-4240-bfce-ce5b7583f038)

**Comment by AdamWr** [comment] 2023-07-13 12:17
I cannot reproduce it if I open provided link, but It looks like a duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/155676
Please read this comment - https://github.com/AdguardTeam/AdguardFilters/issues/155676#issuecomment-1632242206 and below.

**Closed by AdamWr** 2023-07-13 12:17 UTC
