### ISSUE TITLE
downloadfreecourse.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92534] opened 2021-08-26 09:30 UTC
**Issue URL (Annoyance)**:https://downloadfreecourse.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130937418-d7f3c171-3b17-4211-b484-829c9b346353.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-09-03 09:52
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/92295

**Closed by AdamWr** 2021-09-03 09:52 UTC
