### ISSUE TITLE
quora.com [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#11472] opened 2018-02-12 18:54 UTC
**Site**: https://www.quora.com/What-would-happen-if-we-do-not-eat-food-for-two-or-three-days

**Issue**: Please remove the ad seen on the page after login.

**Screenshot**: http://prntscr.com/idrxkx

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.140 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by Nzzyme** [comment] 2018-02-12 18:56
Another sample to test

Site: https://www.quora.com/Will-the-movie-Fifty-Shades-Freed-2018-release-in-India
Screenshot: http://prntscr.com/ids0mx

**Comment by AdamWr** [comment] 2018-02-12 23:31
It is duplicate of this issue - https://github.com/AdguardTeam/AdguardFilters/issues/11251

**Closed by AdamWr** 2018-02-12 23:31 UTC

**Comment by Nzzyme** [comment] 2018-02-13 05:16
Indeed. Thank you!
