### ISSUE TITLE
[Anti-adblock] Viafree.dk

### ISSUE THREAD

**Issue by HUNDO123** [AdguardTeam/AdguardFilters#68024] opened 2020-11-19 20:35 UTC
Hello

Certain pages on viafree.dk does not allow adblock for instance. 1st photo attached beneath.
It keeps loading. I thought it was my internet stability.

In the 2nd photo it turns out it was an anti-adblock.
![Skærmbillede (1912)](https://user-images.githubusercontent.com/49082901/99721013-d7e95000-2aae-11eb-85aa-b5c8da3f3968.png)

https://www.viafree.dk/programmer/reality/politistyrken/saeson-2/episode-5

Can you please help me out I would be forever grateful.

![Skærmbillede (1913)](https://user-images.githubusercontent.com/49082901/99720848-a1abd080-2aae-11eb-918b-d01f1b0b307f.png)

I have been using these filters from way back.

https://github.com/AdguardTeam/AdguardFilters/issues/31803#issuecomment-500923529

**Comment by AdamWr** [comment] 2020-11-20 16:34
It seems that it's duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/68028, so I think it can be closed.

**Closed by AdamWr** 2020-11-20 16:34 UTC
