### ISSUE TITLE
universalfreecourse.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92300] opened 2021-08-24 05:08 UTC
**Issue URL (Annoyance)**:https://universalfreecourse.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130558871-49eb22c0-b42e-4f8c-bd2c-b9a9345fae74.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-08-31 11:31
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/92296

**Closed by AdamWr** 2021-08-31 11:31 UTC
