### ISSUE TITLE
www.indiatoday.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#97996] opened 2021-10-24 15:10 UTC
**Issue URL (Ads)** :https://www.indiatoday.in/india/story/pm-narendra-modi-nation-address-today-live-updates-1867773-2021-10-22

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/138600167-df557856-8162-4cfe-bba5-6ee459c3469e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-11-04 10:26
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/97051

**Closed by AdamWr** 2021-11-04 10:26 UTC
