### ISSUE TITLE
www.indiatoday.in

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#98935] opened 2021-11-04 09:04 UTC
**Issue URL (Ads/Annoyance)**:
 https://www.indiatoday.in/world/story/china-continues-incremental-and-tactical-actions-press-territorial-claims-with-india-pentagon-1873106-2021-11-04

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/140286618-ea66f2a8-2283-4810-871a-2713ab1b64af.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-11-09 13:49
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/98467

**Closed by AdamWr** 2021-11-09 13:49 UTC
