### ISSUE TITLE
http://turbobit.net - fake Download button

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6648] opened 2017-09-08 09:20 UTC
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://turbobit.net 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30204912-ced42d18-948f-11e7-9a41-a99fab620f4d.png)

</details><br/>

***System configuration***

**Filters:**

Eng, Russian, S/media, Spyware, Annoyances, Mobile ads, 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | beta 6.2, extension
AdGuard DNS:                        | None 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment] 2017-09-08 12:31
URL?

**Comment by AdamWr** [comment] 2017-09-11 17:12
I can't reproduce.
I found this link on forum in old topic - http://turbobit.net/download/free/dh7mp1rmnky9

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/30287316-dd32424a-9724-11e7-923c-81280a365fe0.png)

</details>

**Comment by Alex-302** [comment] 2017-09-11 17:23
It was fixed in another issue.

**Closed by Alex-302** 2017-09-11 17:23 UTC
Labels: Ads
