### ISSUE TITLE
https://upbitcoin.com - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4362] opened 2017-02-12 12:34 UTC
https://upbitcoin.com

![image](https://cloud.githubusercontent.com/assets/15856304/22862075/3b7c968e-f130-11e6-8800-2b2e30422ef7.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Stealth mode options(Windows) | On
Adguard filters: | 1 2 3 4 14 201

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1043635

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment] 2017-02-13 11:33
fixed

**Comment by oprotsyk** [comment] 2017-02-14 01:46
repeated again

**Comment by Alex-302** [comment] 2017-02-14 10:39
Can't reproduce. Try to update the filters.

**Comment by Bohdan-SUP** [comment] 2017-02-14 10:52
Fixed now with the update. Thanks!

**Closed by Bohdan-SUP** 2017-02-14 10:52 UTC
Labels: Incorrect Blocking, Resolved
