### ISSUE TITLE
sleazyneasy.com [NSFW] [Ad Banner]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#26194] opened 2018-11-29 13:20 UTC
**Site**: https://www.sleazyneasy.com/videos/1282329/selena-santana-s-experience-with-big-black-cock/?utm_source=donnie&utm_medium=cpm&utm_campaign=sleaz

**Issue**: Please remove the ad banner on the page.

**Screenshot**: http://prntscr.com/lointh

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.110 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment] 2019-01-15 13:48
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/25509

**Closed by AdamWr** 2019-01-15 13:48 UTC
