### ISSUE TITLE
https://m.yelp.com/ - blocked by the content blocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6802] opened 2017-09-17 16:08 UTC
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://m.yelp.com/biz/the-lockspot-cafe-seattle

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30522594-6d6f0aa4-9bdb-11e7-85da-9e0ae5630bce.png)

![image](https://user-images.githubusercontent.com/15856304/30522599-733b44de-9bdb-11e7-84be-2ed283b5f11b.png)

</details><br/>

***Steps to reproduce the problem***:

1. Go to https://m.yelp.com/biz/the-lockspot-cafe-seattle
2. Tap Read more
3. Wait, see it redirecting you to some page which is blocked

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.30.47 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.42 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.9 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.18.20 Enabled=YES
- ID=6 Name="German filter" Version=1.0.36.61 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.64 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1630231

**Comment by evgeniy-ADG** [comment] 2017-10-08 17:29
@AdamWr could you please look into this? We keep receiving complaints on AdGuard blocking yelp.

**Comment by AdamWr** [comment] 2017-10-08 20:58
I looked into this and the problem is that I don't have iPhone and on iPad this website looks different than on screenshot and I see full comments.
On Android it works correctly and redirects me to Google Play.
I guess it also should opens AppStore on iPhone and I found link to to yelp app which is blocked on my iPad.
Could you please ask user if this rule fix it?
`@@||app.adjust.com/*&apple_ct=www.app_pitch.status_quo`
If it won't work, please ask user to check it and send blocked url:
`@@||app.adjust.com^`

**Comment by Alex-302** [comment] 2017-11-05 13:50
@evgeniy-ADG

**Comment by AdamWr** [comment] 2017-12-22 17:47
I think it was fixed in this commit - https://github.com/AdguardTeam/AdguardFilters/commit/7469047729440a5503eccda34d775df3d810ae4f

**Closed by AdamWr** 2017-12-22 17:47 UTC
Labels: N: AdGuard for iOS, T: Incorrect Blocking
