### ISSUE TITLE
avaxgfx.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94267] opened 2021-09-10 16:12 UTC
**Issue URL (Ads/Annoyance)**:https://avaxgfx.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132884617-0f5bf785-b012-4e32-91c9-f2bfd5ba626b.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-09-17 11:30
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/93821

**Closed by AdamWr** 2021-09-17 11:30 UTC
