### ISSUE TITLE
Invalid filter removal request

### ISSUE THREAD

**Issue by xnusnim** [AdguardTeam/AdguardFilters#169825] opened 2024-01-03 05:09 UTC
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

It was infected with adshield and only breakage when I turned on adguard for safari, but I made exceptions to a few filters and it worked normally. So it seems there is a problem with the four domains below.

<hr>
||html-load.com^$popup <br>
||content-laoder.com^$popup<br>
||css-load.com^$popup<br>
||07c225f3.online^$popup<br>
<hr>

## User filter <br>
@@||html-load.com^$popup <br>
@@||content-laoder.com^$popup<br>
@@||css-load.com^$popup<br>
@@||07c225f3.online^$popup<br>
<hr>

## Before applying user filters
https://github.com/AdguardTeam/AdguardFilters/assets/81290656/f3061f18-bb9d-4454-965d-b7219074face

## after applying user filters
https://github.com/AdguardTeam/AdguardFilters/assets/81290656/791c7fb3-74e6-4b71-9012-6dfa5fb63846

### Proposed solution

If you remove that pop-up filter, your web pages will no longer breakage.
<hr>
||html-load.com^$popup <br>
||content-laoder.com^$popup<br>
||css-load.com^$popup<br>
||07c225f3.online^$popup<br>
<hr>

### Additional information

Error Occurrence Conditions

After activating adguard, wait 15 to 20 seconds while refreshing the website. Then the web page is breakage.(Only Safari)
OS : MAC
Browser : safari
adblock : adguard for safari

**Comment by piquark6046** [comment] 2024-01-03 07:44
`$popup` modifier does not block any request in a webpage.
It closes a browser tab that the visited URL is matched.

To resolve your issue, please install [microShield](https://community.list-kr.com/docs/AdGuard/Userscripts/microShield).

**Comment by piquark6046** [comment] 2024-01-03 07:44
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/166433

**Closed by piquark6046** 2024-01-03 07:44 UTC
Labels: Feature Request

**Comment by xnusnim** [comment] 2024-01-04 06:06
@piquark6046 
When there is no `$popup` filter, iframes are inserted successfully. But when the `$popup` filter is applied, iframes are blocked as screenshots below.
It seems the `$popup` filter blocks not only popups but also iframes in Safari.

https://adguard.com/kb/ko/general/ad-filtering/create-own-filters/#popup-modifier
![image](https://github.com/AdguardTeam/AdguardFilters/assets/81290656/9eb76b97-b99a-44ca-8064-e7f4958bb7dd)
`In AdGuard for Safari and iOS, $popup rules simply block the page right away.`
Even Adguard filter rule documentation says that `$popup` filter works differently in Safari and iOS.

This issue seems to be causing damage to the webpage. 
<hr>
<h2>When not using a popup filter</h2>
<img width="758" alt="스크린샷 2024-01-04 오전 10 44 32" src="https://github.com/AdguardTeam/AdguardFilters/assets/81290656/5b32a3ea-c994-4347-98ad-b0e9889222eb">

<h2>When using a popup filter</h2>
<img width="1507" alt="스크린샷 2024-01-04 오전 10 45 20" src="https://github.com/AdguardTeam/AdguardFilters/assets/81290656/4d33ddff-79be-4347-8a13-c1cb27c70961">

---

I'll use microShield with userscripts, but I think there should be many people troubled with this issue using AdGuard in Safari.
Please reopen this issue, and make sure there's no breakage using AdGuard.

**Comment by piquark6046** [comment] 2024-01-04 06:18
The rules are not invalid.
As you said before, Ad-Shield anti-adblock breaks the webpage and lies the visitors that an adblocker breaks the webpage.

**Comment by piquark6046** [comment] 2024-01-04 06:20
And, I don't know why you request continuously even if I replied as https://github.com/AdguardTeam/AdguardFilters/issues/169814#issuecomment-1874783560.
