### ISSUE TITLE
coursef.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93936] opened 2021-09-06 13:29 UTC
**Issue URL (Ads)** :https://www.coursef.com/master-discrete-mathematics-sets-math-logic-and-more-up-to-60-discount-available

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132224702-949b91e9-74a9-4b68-8ce8-b503382aa219.png)
https://www.coursef.com/master-discrete-mathematics-sets-math-logic-and-more-up-to-60-discount-available

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-09-21 08:36
Looks like duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/93062 and https://github.com/AdguardTeam/AdguardFilters/issues/93716

**Closed by AdamWr** 2021-09-21 08:36 UTC
