### ISSUE TITLE
Hope to add a Chinese filter

### ISSUE THREAD

**Issue by loveqqzj** [AdguardTeam/AdguardFilters#37869] opened 2019-08-02 08:40 UTC
Hope to add a chinese filiter, it's very useful for many chinese webpages, his github homepage is https://github.com/YanFung/Ads.
The filiter address is https://raw.githubusercontent.com/YanFung/Ads/master/Mobile.txt
Please help to add it, thanks very much!

**Comment by krystian3w** [comment] 2019-08-03 18:22
Try report also to `CNX Annoyance` / `EasyList China`?

**Comment by krystian3w** [comment] 2019-08-10 13:02
Duplictate of https://github.com/AdguardTeam/FiltersRegistry/issues/216

**Comment by krystian3w** [comment] 2019-08-10 13:03
Duplicate of https://github.com/AdguardTeam/FiltersRegistry/issues/216

**Closed** 2019-08-12 10:06 UTC
