### ISSUE TITLE
tutcourse.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99794] opened 2021-11-12 13:22 UTC
**Issue URL (Ads/Annoyance)**:  `https://tutcourse.com/home-v1/#gsc.tab=0`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141473598-c5a9b262-2c6a-4e9a-9fa8-a53f1f5849c7.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-11-25 10:17
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/99760

**Closed by AdamWr** 2021-11-25 10:17 UTC
Labels: P4: Low
