### ISSUE TITLE
tutcourse.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#99762] opened 2021-11-12 12:06 UTC
**Issue URL (Ads/Annoyance)**:  `https://tutcourse.com/discrete-math-sets-relations-functions-and-math-induction-udemy-free-download/#gsc.tab=0`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141464242-16b2145d-9791-4928-b8e4-da5df7fa9471.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-11-25 10:17
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/99760

**Closed by AdamWr** 2021-11-25 10:17 UTC
Labels: P4: Low
