### ISSUE TITLE
deejay.it

### ISSUE THREAD

**Issue by Oizaro** [AdguardTeam/AdguardFilters#46985] opened 2020-01-02 13:26 UTC
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Video player on the page doesn't appear.

<img src="https://i.ibb.co/Hnp4fzF/Screenshot-20200102-142033-Samsung-Internet-Beta.jpg" alt="Screenshot-20200102-142033-Samsung-Internet-Beta" border="0">
<img src="https://i.ibb.co/pxvqhqV/Screenshot-20200102-142142-Samsung-Internet-Beta.jpg">

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | Android 10
Browser:                               | Samsung Internet 10.2.01.6
AdGuard version:                       | 3.4.11
Filters enabled:                       | Everything except obsolete, privacy and social networks
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Google
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment] 2020-01-02 14:28
Fixed, update should be available in 1-2 hours.

https://github.com/AdguardTeam/AdguardFilters/commit/9109d9783aa81bf1f78e56f869b4d5adac1ce990
https://github.com/AdguardTeam/AdguardFilters/commit/82ebc9041e6bf3b1981aafc2aa4745c4676857c2

Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/46544

**Closed by AdamWr** 2020-01-02 14:28 UTC
