### ISSUE TITLE
http://www.golem.de/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3090] opened 2016-09-27 14:09 UTC
http://www.golem.de/

![image1](https://cloud.githubusercontent.com/assets/15856304/18877186/15f47606-84d5-11e6-9c75-dbb72445425d.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.28 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.74 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.89 Enabled=YES
ID=6 Name="German filter" Version=1.0.27.51 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.33 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.62.93 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.63.8 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.59.14 Enabled=NO
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.19 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.66.8 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
- annoyances filter at my end

**Comment by Alex-302** [comment] 2016-09-27 15:43
Added to Safari filter
```
golem.de###screen > div[id][data-google-query-id]
```

**Comment by osxdoc** [comment] 2016-10-30 13:42
The ad is back again visible on ipad with the rule :-(

**Comment by osxdoc** [comment] 2016-10-30 13:45
Fixed with:
`###screen > div:first-child`

**Comment by Alex-302** [comment] 2016-10-31 10:55
Not shown with German filter enabled
<details>
![image](http://i85.fastpic.ru/big/2016/1031/79/c28e160eef10ac926faec7f180291379.png)
</details>

**Comment by maciboy** [comment] 2017-02-05 09:57
The filter 
###screen > div:first-child
does not work for me anymore :(
Seeing the banner again since a few days.

My filters:
![img_0167](https://cloud.githubusercontent.com/assets/19333006/22625277/d2239d98-eb91-11e6-9e9a-55bfb80c6795.PNG)

**Comment by maciboy** [comment] 2017-02-05 17:12
Hi again,
I investigated the issue and found out, that using uBlock0 on Safari the banner does not show up…

So I Wut through all the list to find the responsible rule there:
It turns out to be this list:
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt

In line 1056 there is the rule:
! https://adblockplus.org/forum/viewtopic.php?f=1&t=49891
**_# golem.de,tweaktown.com##script:inject(abort-on-property-write.js, _sp_)_**

with the corresponding link to the forum.

So please add such a code to Adguard’s list :)
Thank you!

**Comment by Alex-302** [comment] 2017-02-06 19:42
Hi
We need direct link to the page.


> hat using uBlock0 on Safari the banner does not show up

Safari on iOS?

**Comment by osxdoc** [comment] 2017-02-06 20:12
iOS ipad Safari ....iPhone is ok

**Comment by Alex-302** [comment] 2017-02-06 20:15
> iPhone is ok

With Adgurard?



> Only iOS ipad Safari ....

are you sure about uBO for iDevices?

**Comment by maciboy** [comment] 2017-02-06 20:44
Direct Link to page with banner:
https://www.golem.de
It is visible with Adguard on iPads. 

No, of course uBlock for Mac's Safari ;)
I used that to investigate, since there the banner does not show up, when the adblocker is activated. 
I only wanted to help to identify what is the filtering rule.

**Comment by maciboy** [comment] 2017-02-12 15:55
Hi @Alex-302 @evgeniy-ADG ,
any chance to get such a rule into the filter list:
golem.de,tweaktown.com##script:inject(abort-on-property-write.js, sp)

Also, please remove the „resolved“ tag since the issue is ongoing.
Thanks!

**Comment by Alex-302** [comment] 2017-02-13 15:30
Check this rule:
```
golem.de###screen > div[style="min-height: 282px;"]
```

> any chance to get such a rule into the filter list:

JS rules are not supported by iOS content-blocker.

**Comment by maciboy** [comment] 2017-02-14 09:20
Thanks, but unfortunatelly this rule does not help 😢

**Comment by Alex-302** [comment] 2017-02-14 10:35
check this
```
@@||golem.de$generichide
```
are you using full or optimized filters?

**Comment by maciboy** [comment] 2017-02-14 15:02
Again no luck with this one.
The switch "use simplified filters" in the advanced settings is off...

**Comment by Alex-302** [comment] 2017-02-15 11:36
try simplified filters

**Comment by maciboy** [comment] 2017-02-15 22:53
Simplified filters do not help either. Tested with both of the above rules. 
(Is it correct that "@@||golem..." is written in another tone of color than the other rules in the User defined rules?)

**Closed** 2017-07-19 21:40 UTC
Labels: Ads, Cannot Reproduce, iOS Browser
