### ISSUE TITLE
Bing.com cannot open search results

### ISSUE THREAD

**Issue by yokoffing** [AdguardTeam/AdguardFilters#126174] opened 2022-07-25 16:40 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 4.4.0
* Environment name and version: Safari (iOS)
* Operating System: iOS 15.5
* Filters you use in AdGuard: 

   * Adguard mobile ads filter
   * Easylist
  * Easy privacy 
  * AdGuard social media
  * AdGuard annoyances
  * Fanboy annoyances

### Expected Behavior

Successfully navigate to the clicked on search result.

### Actual Behavior

Block page. 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Alex-302** [comment] 2022-08-04 14:35
I can't reproduce this issue.

**Comment by yokoffing** [comment] 2022-08-04 23:37
> probably caused by EasyPrivacy filter. You can disable this filter or replace it with another filter in the Privacy tab as a temporary solution until we find the root of the issue.

The issue goes away when I disable EasyPrivacy. I added AdGuard Tracking Protection filter and I haven’t had issues.

I wonder what’s in EasyPrivacy that’s causing issues with AdGuard and Bing.

**Comment by Alex-302** [comment] 2022-08-05 14:53
@yokoffing Hi. 
This issue is caused by the rule from EasyPrivacy filter, but was fixed in our `AdGuard Tracking Protection` filter(a long time ago)
https://github.com/AdguardTeam/AdguardFilters/commit/501905359f9f07dfdf53b457d980c25232e86014
Please enable it again. Third-party filter authors usually support desktop browsers only(Firefox and Chromium based).
Also Base filter is disabled on your device. We fix many platform-related issues in this filter.
If you prefer to not using AdGuard filters, we cannot help you.

**Closed by Alex-302** 2022-08-05 14:53 UTC
Labels: A: Cannot reproduce, A: In progress, N: AdGuard for iOS
