### ISSUE TITLE
mashable.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#92458] opened 2021-08-25 15:46 UTC
**Issue URL (Ads)** : https://mashable.com/deals/march-23-book-summary-apps

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130821930-5737dacb-8ec1-4d68-8c64-3988aff65c61.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-09-01 11:50
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/92205

**Closed by AdamWr** 2021-09-01 11:50 UTC
