### ISSUE TITLE
avgle.com

### ISSUE THREAD

**Issue by nellem** [AdguardTeam/AdguardFilters#10240] opened 2018-01-22 04:08 UTC
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://avgle.com/video/129900/?adblock_detected

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
![screen shot 2018-01-21 at 11 05 09 pm](https://user-images.githubusercontent.com/35590134/35204936-95bb1908-feff-11e7-9354-27c2cb7c2be8.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Win
Browser:                               | Chrome
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       |  Yes

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment] 2018-01-22 12:56
Duplicate of #7918

**Closed by BlazDT** 2018-01-22 12:56 UTC
Labels: A: Closed
