### ISSUE TITLE
iir.ai [Pop-ups]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#61262] opened 2020-08-10 18:33 UTC
https://iir.ai/ueql8ola

Pop-ups seen on the page before and after solving the captcha. Checked with AG extension for Chrome.

**Comment by AdamWr** [comment] 2020-08-11 09:15
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/61261

**Closed by AdamWr** 2020-08-11 09:15 UTC
