### ISSUE TITLE
rambler.ru ads 

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4666] opened 2017-03-24 14:32 UTC
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

The user has ads on https://www.rambler.ru/ in all the browsers he has (Chrome, Mozilla):

Screenshot:
https://www.dropbox.com/s/9k4dh1rgkgxd1c2/Screenshot%202017-03-24%2013.56.38.png?dl=0

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome, Mozilla
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP 

Stealth mode options(Windows) | on
Adguard filters: | English, Russian, Experimental, Spyware, Annoyances filter
Social media filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1053190

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment] 2017-03-24 19:21
I can't reproduce it.

**Comment by OlegSUP** [comment] 2017-03-25 14:56
Got same trouble. Mac, Chrome, 1.4.1, English, Russian, Experimental, Spyware, Annoyances, Social filter
<details>

![screen shot 2017-03-25 at 4 53 51 pm](https://cloud.githubusercontent.com/assets/26434103/24323251/bf9ca9ca-117b-11e7-8f1a-1dcdcfa2a672.png)
![screen shot 2017-03-25 at 4 54 02 pm](https://cloud.githubusercontent.com/assets/26434103/24323257/cbc84f60-117b-11e7-8d57-dd608e82c128.png)

</details>

**Comment by Darina655** [comment] 2017-03-25 22:45
@Alex-302 mgiganova could reproduce it and requested us to create a case.

**Comment by Alex-302** [comment] 2017-03-26 14:27
It is fixed now.

**Closed by Alex-302** 2017-03-26 14:27 UTC
Labels: Ads
