### ISSUE TITLE
wondershare.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#93433] opened 2021-09-02 15:13 UTC
**Issue URL (Annoyance)**:https://pdf.wondershare.com/word/reverse-text-in-word.html

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131869358-8ba1bf22-6aa4-4e9d-9d65-5e28128dad68.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-09-02 15:15
Looks like duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/93051

**Closed by AdamWr** 2021-09-02 15:15 UTC
