### ISSUE TITLE
avaxgfx.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#94802] opened 2021-09-15 16:03 UTC
**Issue URL (Ads)** :https://avaxgfx.com/tags/Smartest/

<details><summary>Screenshots:</summary>

https://avaxgfx.com/tags/Smartest/
![image](https://user-images.githubusercontent.com/76880977/133468405-5343a902-3135-420a-92e2-2452e2fc30ea.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by AdamWr** [comment] 2021-09-17 11:30
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/93821

**Closed by AdamWr** 2021-09-17 11:30 UTC
