### ISSUE TITLE
pahe.ph (bypass)

### ISSUE THREAD

**Issue by FinderID** [AdguardTeam/AdguardFilters#101009] opened 2021-11-23 15:53 UTC
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Version 3.6.14

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://pahe.ph/venom-let-there-be-carnage-2021-web-hd-480p-720p-1080p/

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

1. https://pahe.ph/venom-let-there-be-carnage-2021-web-hd-480p-720p-1080p/

2. ![image](https://user-images.githubusercontent.com/57831066/143057425-45dc23b0-df51-4e68-9184-58b2de095223.png)

3. please bypass shortlink at the "Download Page", thanks adguard team.

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment] 2021-11-23 15:56
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/99331
Answered here - https://github.com/AdguardTeam/AdguardFilters/issues/99331#issuecomment-972753978

**Closed by AdamWr** 2021-11-23 15:56 UTC
Labels: Unsorted

**Comment by FinderID** [comment] 2021-11-23 19:07
im sorry, i think it can be fixed now

thanks before
