### ISSUE TITLE
fmovies.se

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#12704] opened 2018-03-06 16:58 UTC
***Description***:
* **Current behaviour**: 

Displays ads on main page.
Displays an anti-adblocker on watch subpages.
AdGuard Assistant is disabled on a page (but it's not whitelisted).

<details><summary>Screenshots:</summary>

![fmovies-1](https://user-images.githubusercontent.com/33634917/37046447-1016cfc4-2171-11e8-9d0d-3e4ffe29af1f.PNG)
![fmovies-2](https://user-images.githubusercontent.com/33634917/37046448-1037515e-2171-11e8-9854-681eef9dc6a2.PNG)

</details><br/>

* **Expected behaviour**: 

No ads, no annoyances, etc

***Steps to reproduce the problem***:

1. Simply visit the site

***System configuration***

**Filters:**

English, Russian, Mobile, Experimental, Annoyances, Adblock Warning Removal list

Information                            | Value
---                                    | ---
Operating system:                      | Windows 8.1
Browser:                               | Chrome 65 beta
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Russian, Mobile, Experimental, Annoyances, Adblock Warning Removal list
Windows-specific details:        | HTTPS filtering enabled, TDI driver
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 1780428 - iOS repro

**Comment by BlazDT** [comment] 2018-03-08 04:11
Ads not reproduced. Popup fixed.
Adblock message is even showing without any blockers, fixed in Annoyance filter.

@AdamWr please check for ads.

**Comment by AdamWr** [comment] 2018-03-08 11:42
I can't reproduce ads on Windows and iOS.
Added rules to block popups on iOS.

@Alex-302 Could you please check it?

**Comment by Alex-302** [comment] 2018-03-08 16:06
Added
```
fmovies.se##div[style="display: block;height:166px;overflow:hidden"]
```

**Closed by Alex-302** 2018-03-08 16:06 UTC
Labels: N: AdGuard for Windows, N: AdGuard for iOS, P4: Low, T: Ads, T: Anti Adblock Script
